typedef char gchar;
typedef int gint;
typedef int guint;
typedef bool gboolean;
typedef unsigned char guchar;
typedef long glong;
typedef unsigned long gulong;
typedef float gfloat;
typedef double gdouble;
typedef int8_t gint8;
typedef uint8_t guint8;
typedef int16_t gint16;
typedef uint16_t guint16;
typedef int32_t gint32;
typedef uint32_t guint32;
typedef void* gpointer;
typedef guint32 gunichar;
typedef signed long gssize;