typedef enum {
    G_CONNECT_AFTER = 1 << 0,
    G_CONNECT_SWAPPED = 1 << 1
} GConnectFlags;

typedef enum {
    G_SIGNAL_RUN_FIRST = 1 << 0,
    G_SIGNAL_RUN_LAST = 1 << 1,
    G_SIGNAL_RUN_CLEANUP = 1 << 2,
    G_SIGNAL_NO_RECURSE = 1 << 3,
    G_SIGNAL_DETAILED = 1 << 4,
    G_SIGNAL_ACTION = 1 << 5,
    G_SIGNAL_NO_HOOKS = 1 << 6,
    G_SIGNAL_MUST_COLLECT = 1 << 7,
    G_SIGNAL_DEPRECATED = 1 << 8
} GSignalFlags;

typedef enum {
  GTK_POS_LEFT,
  GTK_POS_RIGHT,
  GTK_POS_TOP,
  GTK_POS_BOTTOM
} GtkPositionType;

typedef enum {
  GTK_DIALOG_MODAL,
  GTK_DIALOG_DESTROY_WITH_PARENT,
  GTK_DIALOG_USE_HEADER_BAR,
} GtkDialogFlags;

typedef enum {
  GTK_APPLICATION_INHIBIT_LOGOUT,
  GTK_APPLICATION_INHIBIT_SWITCH,
  GTK_APPLICATION_INHIBIT_SUSPEND,
  GTK_APPLICATION_INHIBIT_IDLE,
} GtkApplicationInhibitFlags;

typedef enum {
  GTK_ASSISTANT_PAGE_CONTENT,
  GTK_ASSISTANT_PAGE_INTRO,
  GTK_ASSISTANT_PAGE_CONFIRM,
  GTK_ASSISTANT_PAGE_SUMMARY,
  GTK_ASSISTANT_PAGE_PROGRESS,
  GTK_ASSISTANT_PAGE_CUSTOM,
} GtkAssistantPageType;

typedef enum {
  GTK_CELL_RENDERER_SELECTED,
  GTK_CELL_RENDERER_PRELIT,
  GTK_CELL_RENDERER_INSENSITIVE,
  GTK_CELL_RENDERER_SORTED,
  GTK_CELL_RENDERER_FOCUSED,
  GTK_CELL_RENDERER_EXPANDABLE,
  GTK_CELL_RENDERER_EXPANDED,
} GtkCellRendererState;

typedef enum {
  GTK_BUILDER_CLOSURE_SWAPPED,
} GtkBuilderClosureFlags;

typedef enum {
  GTK_SENSITIVITY_AUTO,
  GTK_SENSITIVITY_ON,
  GTK_SENSITIVITY_OFF,
} GtkSensitivityType;

typedef enum {
  GTK_SORT_ASCENDING,
  GTK_SORT_DESCENDING,
} GtkSortType;

typedef enum {
  G_APPLICATION_FLAGS_NONE,
  G_APPLICATION_IS_SERVICE,
  G_APPLICATION_IS_LAUNCHER,
  G_APPLICATION_HANDLES_OPEN,
  G_APPLICATION_HANDLES_COMMAND_LINE,
  G_APPLICATION_SEND_ENVIRONMENT,
  G_APPLICATION_NON_UNIQUE,
  G_APPLICATION_CAN_OVERRIDE_APP_ID,
  G_APPLICATION_ALLOW_REPLACEMENT,
  G_APPLICATION_REPLACE,
} GApplicationFlags;

typedef enum {
  GTK_ORIENTATION_HORIZONTAL,
  GTK_ORIENTATION_VERTICAL,
} GtkOrientation;

typedef enum {
  GTK_SELECTION_NONE,
  GTK_SELECTION_SINGLE,
  GTK_SELECTION_BROWSE,
  GTK_SELECTION_MULTIPLE,
} GtkSelectionMode;

typedef enum {
GTK_STACK_TRANSITION_TYPE_NONE,
GTK_STACK_TRANSITION_TYPE_CROSSFADE,
GTK_STACK_TRANSITION_TYPE_SLIDE_RIGHT,
GTK_STACK_TRANSITION_TYPE_SLIDE_LEFT,
GTK_STACK_TRANSITION_TYPE_SLIDE_UP,
GTK_STACK_TRANSITION_TYPE_SLIDE_DOWN,
GTK_STACK_TRANSITION_TYPE_SLIDE_LEFT_RIGHT,
GTK_STACK_TRANSITION_TYPE_SLIDE_UP_DOWN,
GTK_STACK_TRANSITION_TYPE_OVER_UP,
GTK_STACK_TRANSITION_TYPE_OVER_DOWN,
GTK_STACK_TRANSITION_TYPE_OVER_LEFT,
GTK_STACK_TRANSITION_TYPE_OVER_RIGHT,
GTK_STACK_TRANSITION_TYPE_UNDER_UP,
GTK_STACK_TRANSITION_TYPE_UNDER_DOWN,
GTK_STACK_TRANSITION_TYPE_UNDER_LEFT,
GTK_STACK_TRANSITION_TYPE_UNDER_RIGHT,
GTK_STACK_TRANSITION_TYPE_OVER_UP_DOWN,
GTK_STACK_TRANSITION_TYPE_OVER_DOWN_UP,
GTK_STACK_TRANSITION_TYPE_OVER_LEFT_RIGHT,
GTK_STACK_TRANSITION_TYPE_OVER_RIGHT_LEFT,
GTK_STACK_TRANSITION_TYPE_ROTATE_LEFT,
GTK_STACK_TRANSITION_TYPE_ROTATE_RIGHT,
GTK_STACK_TRANSITION_TYPE_ROTATE_LEFT_RIGHT
} GtkStackTransitionType;

typedef enum {
  GTK_POLICY_ALWAYS,
  GTK_POLICY_AUTOMATIC,
  GTK_POLICY_NEVER,
  GTK_POLICY_EXTERNAL,
} GtkPolicyType;

typedef enum {
  GTK_DIR_TAB_FORWARD,
  GTK_DIR_TAB_BACKWARD,
  GTK_DIR_UP,
  GTK_DIR_DOWN,
  GTK_DIR_LEFT,
  GTK_DIR_RIGHT,
} GtkDirectionType;

typedef enum {
  GTK_SIZE_REQUEST_HEIGHT_FOR_WIDTH,
  GTK_SIZE_REQUEST_WIDTH_FOR_HEIGHT,
  GTK_SIZE_REQUEST_CONSTANT_SIZE,
} GtkSizeRequestMode;

typedef enum {
  GTK_STATE_FLAG_NORMAL,
  GTK_STATE_FLAG_ACTIVE,
  GTK_STATE_FLAG_PRELIGHT,
  GTK_STATE_FLAG_SELECTED,
  GTK_STATE_FLAG_INSENSITIVE,
  GTK_STATE_FLAG_INCONSISTENT,
  GTK_STATE_FLAG_FOCUSED,
  GTK_STATE_FLAG_BACKDROP,
  GTK_STATE_FLAG_DIR_LTR,
  GTK_STATE_FLAG_DIR_RTL,
  GTK_STATE_FLAG_LINK,
  GTK_STATE_FLAG_VISITED,
  GTK_STATE_FLAG_CHECKED,
  GTK_STATE_FLAG_DROP_ACTIVE,
} GtkStateFlags;

typedef enum {
  GTK_PICK_DEFAULT,
  GTK_PICK_INSENSITIVE,
  GTK_PICK_NON_TARGETABLE,
} GtkPickFlags;

typedef enum {
  GDK_SHIFT_MASK,
  GDK_LOCK_MASK,
  GDK_CONTROL_MASK,
  GDK_ALT_MASK,
  GDK_BUTTON1_MASK,
  GDK_BUTTON2_MASK,
  GDK_BUTTON3_MASK,
  GDK_BUTTON4_MASK,
  GDK_BUTTON5_MASK,
  GDK_SUPER_MASK,
  GDK_HYPER_MASK,
  GDK_META_MASK,
} GdkModifierType;

typedef enum {
  GTK_BASELINE_POSITION_TOP,
  GTK_BASELINE_POSITION_CENTER,
  GTK_BASELINE_POSITION_BOTTOM,
} GtkBaselinePosition;

typedef enum {
  GTK_CORNER_TOP_LEFT,
  GTK_CORNER_BOTTOM_LEFT,
  GTK_CORNER_TOP_RIGHT,
  GTK_CORNER_BOTTOM_RIGHT,
} GtkCornerType;

typedef enum {
  PANGO_ELLIPSIZE_NONE,
  PANGO_ELLIPSIZE_START,
  PANGO_ELLIPSIZE_MIDDLE,
  PANGO_ELLIPSIZE_END,
} PangoEllipsizeMode;

typedef enum {
  GTK_ENTRY_ICON_PRIMARY,
  GTK_ENTRY_ICON_SECONDARY,
} GtkEntryIconPosition;

typedef enum {
  GTK_IMAGE_EMPTY,
  GTK_IMAGE_ICON_NAME,
  GTK_IMAGE_GICON,
  GTK_IMAGE_PAINTABLE,
} GtkImageType;

typedef enum {
  GTK_INPUT_HINT_NONE,
  GTK_INPUT_HINT_SPELLCHECK,
  GTK_INPUT_HINT_NO_SPELLCHECK,
  GTK_INPUT_HINT_WORD_COMPLETION,
  GTK_INPUT_HINT_LOWERCASE,
  GTK_INPUT_HINT_UPPERCASE_CHARS,
  GTK_INPUT_HINT_UPPERCASE_WORDS,
  GTK_INPUT_HINT_UPPERCASE_SENTENCES,
  GTK_INPUT_HINT_INHIBIT_OSK,
  GTK_INPUT_HINT_VERTICAL_WRITING,
  GTK_INPUT_HINT_EMOJI,
  GTK_INPUT_HINT_NO_EMOJI,
  GTK_INPUT_HINT_PRIVATE,
} GtkInputHints;

typedef enum {
  GTK_INPUT_PURPOSE_FREE_FORM,
  GTK_INPUT_PURPOSE_ALPHA,
  GTK_INPUT_PURPOSE_DIGITS,
  GTK_INPUT_PURPOSE_NUMBER,
  GTK_INPUT_PURPOSE_PHONE,
  GTK_INPUT_PURPOSE_URL,
  GTK_INPUT_PURPOSE_EMAIL,
  GTK_INPUT_PURPOSE_NAME,
  GTK_INPUT_PURPOSE_PASSWORD,
  GTK_INPUT_PURPOSE_PIN,
  GTK_INPUT_PURPOSE_TERMINAL,
} GtkInputPurpose;

typedef enum {
  GTK_ACCESSIBLE_ROLE_ALERT,
  GTK_ACCESSIBLE_ROLE_ALERT_DIALOG,
  GTK_ACCESSIBLE_ROLE_BANNER,
  GTK_ACCESSIBLE_ROLE_BUTTON,
  GTK_ACCESSIBLE_ROLE_CAPTION,
  GTK_ACCESSIBLE_ROLE_CELL,
  GTK_ACCESSIBLE_ROLE_CHECKBOX,
  GTK_ACCESSIBLE_ROLE_COLUMN_HEADER,
  GTK_ACCESSIBLE_ROLE_COMBO_BOX,
  GTK_ACCESSIBLE_ROLE_COMMAND,
  GTK_ACCESSIBLE_ROLE_COMPOSITE,
  GTK_ACCESSIBLE_ROLE_DIALOG,
  GTK_ACCESSIBLE_ROLE_DOCUMENT,
  GTK_ACCESSIBLE_ROLE_FEED,
  GTK_ACCESSIBLE_ROLE_FORM,
  GTK_ACCESSIBLE_ROLE_GENERIC,
  GTK_ACCESSIBLE_ROLE_GRID,
  GTK_ACCESSIBLE_ROLE_GRID_CELL,
  GTK_ACCESSIBLE_ROLE_GROUP,
  GTK_ACCESSIBLE_ROLE_HEADING,
  GTK_ACCESSIBLE_ROLE_IMG,
  GTK_ACCESSIBLE_ROLE_INPUT,
  GTK_ACCESSIBLE_ROLE_LABEL,
  GTK_ACCESSIBLE_ROLE_LANDMARK,
  GTK_ACCESSIBLE_ROLE_LEGEND,
  GTK_ACCESSIBLE_ROLE_LINK,
  GTK_ACCESSIBLE_ROLE_LIST,
  GTK_ACCESSIBLE_ROLE_LIST_BOX,
  GTK_ACCESSIBLE_ROLE_LIST_ITEM,
  GTK_ACCESSIBLE_ROLE_LOG,
  GTK_ACCESSIBLE_ROLE_MAIN,
  GTK_ACCESSIBLE_ROLE_MARQUEE,
  GTK_ACCESSIBLE_ROLE_MATH,
  GTK_ACCESSIBLE_ROLE_METER,
  GTK_ACCESSIBLE_ROLE_MENU,
  GTK_ACCESSIBLE_ROLE_MENU_BAR,
  GTK_ACCESSIBLE_ROLE_MENU_ITEM,
  GTK_ACCESSIBLE_ROLE_MENU_ITEM_CHECKBOX,
  GTK_ACCESSIBLE_ROLE_MENU_ITEM_RADIO,
  GTK_ACCESSIBLE_ROLE_NAVIGATION,
  GTK_ACCESSIBLE_ROLE_NONE,
  GTK_ACCESSIBLE_ROLE_NOTE,
  GTK_ACCESSIBLE_ROLE_OPTION,
  GTK_ACCESSIBLE_ROLE_PRESENTATION,
  GTK_ACCESSIBLE_ROLE_PROGRESS_BAR,
  GTK_ACCESSIBLE_ROLE_RADIO,
  GTK_ACCESSIBLE_ROLE_RADIO_GROUP,
  GTK_ACCESSIBLE_ROLE_RANGE,
  GTK_ACCESSIBLE_ROLE_REGION,
  GTK_ACCESSIBLE_ROLE_ROW,
  GTK_ACCESSIBLE_ROLE_ROW_GROUP,
  GTK_ACCESSIBLE_ROLE_ROW_HEADER,
  GTK_ACCESSIBLE_ROLE_SCROLLBAR,
  GTK_ACCESSIBLE_ROLE_SEARCH,
  GTK_ACCESSIBLE_ROLE_SEARCH_BOX,
  GTK_ACCESSIBLE_ROLE_SECTION,
  GTK_ACCESSIBLE_ROLE_SECTION_HEAD,
  GTK_ACCESSIBLE_ROLE_SELECT,
  GTK_ACCESSIBLE_ROLE_SEPARATOR,
  GTK_ACCESSIBLE_ROLE_SLIDER,
  GTK_ACCESSIBLE_ROLE_SPIN_BUTTON,
  GTK_ACCESSIBLE_ROLE_STATUS,
  GTK_ACCESSIBLE_ROLE_STRUCTURE,
  GTK_ACCESSIBLE_ROLE_SWITCH,
  GTK_ACCESSIBLE_ROLE_TAB,
  GTK_ACCESSIBLE_ROLE_TABLE,
  GTK_ACCESSIBLE_ROLE_TAB_LIST,
  GTK_ACCESSIBLE_ROLE_TAB_PANEL,
  GTK_ACCESSIBLE_ROLE_TEXT_BOX,
  GTK_ACCESSIBLE_ROLE_TIME,
  GTK_ACCESSIBLE_ROLE_TIMER,
  GTK_ACCESSIBLE_ROLE_TOOLBAR,
  GTK_ACCESSIBLE_ROLE_TOOLTIP,
  GTK_ACCESSIBLE_ROLE_TREE,
  GTK_ACCESSIBLE_ROLE_TREE_GRID,
  GTK_ACCESSIBLE_ROLE_TREE_ITEM,
  GTK_ACCESSIBLE_ROLE_WIDGET,
  GTK_ACCESSIBLE_ROLE_WINDOW,
} GtkAccessibleRole;

typedef enum {
  GTK_EVENT_CONTROLLER_SCROLL_NONE,
  GTK_EVENT_CONTROLLER_SCROLL_VERTICAL,
  GTK_EVENT_CONTROLLER_SCROLL_HORIZONTAL,
  GTK_EVENT_CONTROLLER_SCROLL_DISCRETE,
  GTK_EVENT_CONTROLLER_SCROLL_KINETIC,
  GTK_EVENT_CONTROLLER_SCROLL_BOTH_AXES,
} GtkEventControllerScrollFlags;

typedef enum {
  GTK_ICON_LOOKUP_FORCE_REGULAR,
  GTK_ICON_LOOKUP_FORCE_SYMBOLIC,
  GTK_ICON_LOOKUP_PRELOAD
} GtkIconLookupFlags;

typedef enum {
  GTK_ICON_VIEW_NO_DROP,
  GTK_ICON_VIEW_DROP_INTO,
  GTK_ICON_VIEW_DROP_LEFT,
  GTK_ICON_VIEW_DROP_RIGHT,
  GTK_ICON_VIEW_DROP_ABOVE,
  GTK_ICON_VIEW_DROP_BELOW,
} GtkIconViewDropPosition;

typedef enum {
  GTK_ICON_SIZE_INHERIT,
  GTK_ICON_SIZE_NORMAL,
  GTK_ICON_SIZE_LARGE,
} GtkIconSize;

typedef enum {
  GTK_MESSAGE_INFO,
  GTK_MESSAGE_WARNING,
  GTK_MESSAGE_QUESTION,
  GTK_MESSAGE_ERROR,
  GTK_MESSAGE_OTHER,
} GtkMessageType;

typedef enum {
    GTK_CONSTRAINT_ATTRIBUTE_NONE,
    GTK_CONSTRAINT_ATTRIBUTE_LEFT,
    GTK_CONSTRAINT_ATTRIBUTE_RIGHT,
    GTK_CONSTRAINT_ATTRIBUTE_TOP,
    GTK_CONSTRAINT_ATTRIBUTE_BOTTOM,
    GTK_CONSTRAINT_ATTRIBUTE_START,
    GTK_CONSTRAINT_ATTRIBUTE_END,
    GTK_CONSTRAINT_ATTRIBUTE_WIDTH,
    GTK_CONSTRAINT_ATTRIBUTE_HEIGHT,
    GTK_CONSTRAINT_ATTRIBUTE_CENTER_X,
    GTK_CONSTRAINT_ATTRIBUTE_CENTER_Y,
    GTK_CONSTRAINT_ATTRIBUTE_BASELINE,
} GtkConstraintAttribute;

typedef enum {
    GTK_CONSTRAINT_RELATION_LE,
    GTK_CONSTRAINT_RELATION_EQ,
    GTK_CONSTRAINT_RELATION_GE
} GtkConstraintRelation;

typedef enum {
    GTK_CONSTRAINT_STRENGTH_REQUIRED,
    GTK_CONSTRAINT_STRENGTH_STRONG,
    GTK_CONSTRAINT_STRENGTH_MEDIUM,
    GTK_CONSTRAINT_STRENGTH_WEAK
} GtkConstraintStrength;

typedef enum {
    GTK_LIMIT_NONE,
    GTK_LIMIT_SAME_NATIVE,
} GtkPropagationLimit;

typedef enum {
    GTK_FILTER_MATCH_SOME,
    GTK_FILTER_MATCH_NONE,
    GTK_FILTER_MATCH_ALL,
} GtkFilterMatch;

typedef enum {
    GTK_FILTER_CHANGE_DIFFERENT,
    GTK_FILTER_CHANGE_LESS_STRICT,
    GTK_FILTER_CHANGE_MORE_STRICT,
} GtkFilterChange;

typedef enum {
    GTK_INSCRIPTION_OVERFLOW_CLIP,
    GTK_INSCRIPTION_OVERFLOW_ELLIPSIZE_START,
    GTK_INSCRIPTION_OVERFLOW_ELLIPSIZE_MIDDLE,
    GTK_INSCRIPTION_OVERFLOW_ELLIPSIZE_END,
} GtkInscriptionOverflow;

typedef enum {
    GTK_NATURAL_WRAP_INHERIT,
    GTK_NATURAL_WRAP_NONE,
    GTK_NATURAL_WRAP_WORD,
} GtkNaturalWrapMode;

typedef enum {
    GTK_CONTENT_FIT_FILL,
    GTK_CONTENT_FIT_CONTAIN,
    GTK_CONTENT_FIT_COVER,
    GTK_CONTENT_FIT_SCALE_DOWN,
} GtkContentFit;

typedef enum {
    GTK_POPOVER_MENU_NESTED
} GtkPopoverMenuFlags;

typedef enum {
    GTK_PRINT_CAPABILITY_PAGE_SET,
    GTK_PRINT_CAPABILITY_COPIES,
    GTK_PRINT_CAPABILITY_COLLATE,
    GTK_PRINT_CAPABILITY_REVERSE,
    GTK_PRINT_CAPABILITY_SCALE,
    GTK_PRINT_CAPABILITY_GENERATE_PDF,
    GTK_PRINT_CAPABILITY_GENERATE_PS,
    GTK_PRINT_CAPABILITY_PREVIEW,
    GTK_PRINT_CAPABILITY_NUMBER_UP,
    GTK_PRINT_CAPABILITY_NUMBER_UP_LAYOUT,
} GtkPrintCapabilities;

typedef enum {
    GTK_SHORTCUT_ACTION_EXCLUSIVE
} GtkShortcutActionFlags;

typedef enum {
    GTK_ORDERING_SMALLER,
    GTK_ORDERING_EQUAL,
    GTK_ORDERING_LARGER,
} GtkOrdering;

typedef enum {
    GTK_SORTER_CHANGE_DIFFERENT,
    GTK_SORTER_CHANGE_INVERTED,
    GTK_SORTER_CHANGE_LESS_STRICT,
    GTK_SORTER_CHANGE_MORE_STRICT,
} GtkSorterChange;

typedef enum {
    GTK_SORTER_ORDER_PARTIAL,
    GTK_SORTER_ORDER_NONE,
    GTK_SORTER_ORDER_TOTAL,
} GtkSorterOrder;

typedef enum {
    GTK_STRING_FILTER_MATCH_MODE_EXACT,
    GTK_STRING_FILTER_MATCH_MODE_SUBSTRING,
    GTK_STRING_FILTER_MATCH_MODE_PREFIX,
} GtkStringFilterMatchMode;
