extern GtkWidget* gtk_scrolled_window_get_child ( GtkScrolledWindow* scrolled_window );
extern GtkWidget* gtk_scrolled_window_new ( void );
extern GtkAdjustment* gtk_scrolled_window_get_hadjustment ( GtkScrolledWindow* scrolled_window );
extern gboolean gtk_scrolled_window_get_has_frame ( GtkScrolledWindow* scrolled_window );
extern int gtk_scrolled_window_get_max_content_height ( GtkScrolledWindow* scrolled_window );
extern gboolean gtk_scrolled_window_get_kinetic_scrolling ( GtkScrolledWindow* scrolled_window );
extern int gtk_scrolled_window_get_min_content_height ( GtkScrolledWindow* scrolled_window );
extern GtkWidget* gtk_scrolled_window_get_hscrollbar ( GtkScrolledWindow* scrolled_window );
extern int gtk_scrolled_window_get_min_content_width ( GtkScrolledWindow* scrolled_window );
extern gboolean gtk_scrolled_window_get_overlay_scrolling ( GtkScrolledWindow* scrolled_window );
extern GtkCornerType gtk_scrolled_window_get_placement ( GtkScrolledWindow* scrolled_window );
extern void gtk_scrolled_window_get_policy ( GtkScrolledWindow* scrolled_window, GtkPolicyType* hscrollbar_policy, GtkPolicyType* vscrollbar_policy );
extern int gtk_scrolled_window_get_max_content_width ( GtkScrolledWindow* scrolled_window );
extern gboolean gtk_scrolled_window_get_propagate_natural_height ( GtkScrolledWindow* scrolled_window );
extern GtkWidget* gtk_scrolled_window_get_vscrollbar ( GtkScrolledWindow* scrolled_window );
extern GtkAdjustment* gtk_scrolled_window_get_vadjustment ( GtkScrolledWindow* scrolled_window );
extern void gtk_scrolled_window_set_hadjustment ( GtkScrolledWindow* scrolled_window, GtkAdjustment* hadjustment );
extern gboolean gtk_scrolled_window_get_propagate_natural_width ( GtkScrolledWindow* scrolled_window );
extern void gtk_scrolled_window_set_has_frame ( GtkScrolledWindow* scrolled_window, gboolean has_frame );
extern void gtk_scrolled_window_set_max_content_width ( GtkScrolledWindow* scrolled_window, int width );
extern void gtk_scrolled_window_set_min_content_height ( GtkScrolledWindow* scrolled_window, int height );
extern void gtk_scrolled_window_set_kinetic_scrolling ( GtkScrolledWindow* scrolled_window, gboolean kinetic_scrolling );
extern void gtk_scrolled_window_set_child ( GtkScrolledWindow* scrolled_window, GtkWidget* child );
extern void gtk_scrolled_window_set_max_content_height ( GtkScrolledWindow* scrolled_window, int height );
extern void gtk_scrolled_window_set_min_content_width ( GtkScrolledWindow* scrolled_window, int width );
extern void gtk_scrolled_window_set_overlay_scrolling ( GtkScrolledWindow* scrolled_window, gboolean overlay_scrolling );
extern void gtk_scrolled_window_set_placement ( GtkScrolledWindow* scrolled_window, GtkCornerType window_placement );
extern void gtk_scrolled_window_set_propagate_natural_height ( GtkScrolledWindow* scrolled_window, gboolean propagate );
extern void gtk_scrolled_window_set_propagate_natural_width ( GtkScrolledWindow* scrolled_window, gboolean propagate );
extern void gtk_scrolled_window_set_policy ( GtkScrolledWindow* scrolled_window, GtkPolicyType hscrollbar_policy, GtkPolicyType vscrollbar_policy );
extern void gtk_scrolled_window_set_vadjustment ( GtkScrolledWindow* scrolled_window, GtkAdjustment* vadjustment );
extern void gtk_scrolled_window_unset_placement ( GtkScrolledWindow* scrolled_window );
