extern GtkPageSetup* gtk_page_setup_new ( void );
extern GtkPageSetup* gtk_page_setup_new_from_key_file ( GKeyFile* key_file, const char* group_name, GError** error );
extern GtkPageSetup* gtk_page_setup_new_from_gvariant ( GVariant* variant );
extern GtkPageSetup* gtk_page_setup_new_from_file ( const char* file_name, GError** error );
extern double gtk_page_setup_get_bottom_margin ( GtkPageSetup* setup, GtkUnit unit );
extern GtkPageSetup* gtk_page_setup_copy ( GtkPageSetup* other );
extern double gtk_page_setup_get_left_margin ( GtkPageSetup* setup, GtkUnit unit );
extern double gtk_page_setup_get_page_height ( GtkPageSetup* setup, GtkUnit unit );
extern double gtk_page_setup_get_page_width ( GtkPageSetup* setup, GtkUnit unit );
extern GtkPaperSize* gtk_page_setup_get_paper_size ( GtkPageSetup* setup );
extern GtkPageOrientation gtk_page_setup_get_orientation ( GtkPageSetup* setup );
extern double gtk_page_setup_get_paper_height ( GtkPageSetup* setup, GtkUnit unit );
extern double gtk_page_setup_get_right_margin ( GtkPageSetup* setup, GtkUnit unit );
extern double gtk_page_setup_get_paper_width ( GtkPageSetup* setup, GtkUnit unit );
extern double gtk_page_setup_get_top_margin ( GtkPageSetup* setup, GtkUnit unit );
extern void gtk_page_setup_set_bottom_margin ( GtkPageSetup* setup, double margin, GtkUnit unit );
extern gboolean gtk_page_setup_load_file ( GtkPageSetup* setup, const char* file_name, GError** error );
extern gboolean gtk_page_setup_load_key_file ( GtkPageSetup* setup, GKeyFile* key_file, const char* group_name, GError** error );
extern void gtk_page_setup_set_orientation ( GtkPageSetup* setup, GtkPageOrientation orientation );
extern void gtk_page_setup_set_paper_size_and_default_margins ( GtkPageSetup* setup, GtkPaperSize* size );
extern void gtk_page_setup_set_paper_size ( GtkPageSetup* setup, GtkPaperSize* size );
extern void gtk_page_setup_set_right_margin ( GtkPageSetup* setup, double margin, GtkUnit unit );
extern void gtk_page_setup_set_top_margin ( GtkPageSetup* setup, double margin, GtkUnit unit );
extern void gtk_page_setup_set_left_margin ( GtkPageSetup* setup, double margin, GtkUnit unit );
extern GVariant* gtk_page_setup_to_gvariant ( GtkPageSetup* setup );
extern void gtk_page_setup_to_key_file ( GtkPageSetup* setup, GKeyFile* key_file, const char* group_name );
extern gboolean gtk_page_setup_to_file ( GtkPageSetup* setup, const char* file_name, GError** error );
