extern void gtk_list_box_drag_highlight_row ( GtkListBox* box, GtkListBoxRow* row );
extern GtkWidget* gtk_list_box_new ( void );
extern void gtk_list_box_append ( GtkListBox* box, GtkWidget* child );
extern void gtk_list_box_bind_model ( GtkListBox* box, GListModel* model, GtkListBoxCreateWidgetFunc create_widget_func, gpointer user_data, GDestroyNotify user_data_free_func );
extern gboolean gtk_list_box_get_activate_on_single_click ( GtkListBox* box );
extern GtkListBoxRow* gtk_list_box_get_row_at_index ( GtkListBox* box, int index_ );
extern GtkListBoxRow* gtk_list_box_get_row_at_y ( GtkListBox* box, int y );
extern GtkAdjustment* gtk_list_box_get_adjustment ( GtkListBox* box );
extern void gtk_list_box_drag_unhighlight_row ( GtkListBox* box );
extern GtkListBoxRow* gtk_list_box_get_selected_row ( GtkListBox* box );
extern void gtk_list_box_insert ( GtkListBox* box, GtkWidget* child, int position );
extern gboolean gtk_list_box_get_show_separators ( GtkListBox* box );
extern GtkSelectionMode gtk_list_box_get_selection_mode ( GtkListBox* box );
extern GList* gtk_list_box_get_selected_rows ( GtkListBox* box );
extern void gtk_list_box_invalidate_sort ( GtkListBox* box );
extern void gtk_list_box_invalidate_headers ( GtkListBox* box );
extern void gtk_list_box_remove ( GtkListBox* box, GtkWidget* child );
extern void gtk_list_box_invalidate_filter ( GtkListBox* box );
extern void gtk_list_box_select_all ( GtkListBox* box );
extern void gtk_list_box_selected_foreach ( GtkListBox* box, GtkListBoxForeachFunc func, gpointer data );
extern void gtk_list_box_select_row ( GtkListBox* box, GtkListBoxRow* row );
extern void gtk_list_box_prepend ( GtkListBox* box, GtkWidget* child );
extern void gtk_list_box_set_activate_on_single_click ( GtkListBox* box, gboolean single );
extern void gtk_list_box_set_placeholder ( GtkListBox* box, GtkWidget* placeholder );
extern void gtk_list_box_set_filter_func ( GtkListBox* box, GtkListBoxFilterFunc filter_func, gpointer user_data, GDestroyNotify destroy );
extern void gtk_list_box_set_adjustment ( GtkListBox* box, GtkAdjustment* adjustment );
extern void gtk_list_box_set_header_func ( GtkListBox* box, GtkListBoxUpdateHeaderFunc update_header, gpointer user_data, GDestroyNotify destroy );
extern void gtk_list_box_set_selection_mode ( GtkListBox* box, GtkSelectionMode mode );
extern void gtk_list_box_set_sort_func ( GtkListBox* box, GtkListBoxSortFunc sort_func, gpointer user_data, GDestroyNotify destroy );
extern void gtk_list_box_set_show_separators ( GtkListBox* box, gboolean show_separators );
extern void gtk_list_box_unselect_all ( GtkListBox* box );
extern void gtk_list_box_unselect_row ( GtkListBox* box, GtkListBoxRow* row );
