extern GtkWidget* gtk_about_dialog_new ( void );
extern const char* gtk_about_dialog_get_copyright ( GtkAboutDialog* about );
extern const char* const* gtk_about_dialog_get_artists ( GtkAboutDialog* about );
extern const char* const* gtk_about_dialog_get_documenters ( GtkAboutDialog* about );
extern void gtk_about_dialog_add_credit_section ( GtkAboutDialog* about, const char* section_name, const char** people );
extern const char* const* gtk_about_dialog_get_authors ( GtkAboutDialog* about );
extern const char* gtk_about_dialog_get_comments ( GtkAboutDialog* about );
extern GtkLicense gtk_about_dialog_get_license_type ( GtkAboutDialog* about );
extern GdkPaintable* gtk_about_dialog_get_logo ( GtkAboutDialog* about );
extern const char* gtk_about_dialog_get_license ( GtkAboutDialog* about );
extern const char* gtk_about_dialog_get_system_information ( GtkAboutDialog* about );
extern const char* gtk_about_dialog_get_logo_icon_name ( GtkAboutDialog* about );
extern const char* gtk_about_dialog_get_program_name ( GtkAboutDialog* about );
extern const char* gtk_about_dialog_get_translator_credits ( GtkAboutDialog* about );
extern gboolean gtk_about_dialog_get_wrap_license ( GtkAboutDialog* about );
extern const char* gtk_about_dialog_get_website ( GtkAboutDialog* about );
extern const char* gtk_about_dialog_get_website_label ( GtkAboutDialog* about );
extern void gtk_about_dialog_set_comments ( GtkAboutDialog* about, const char* comments );
extern void gtk_about_dialog_set_artists ( GtkAboutDialog* about, const char** artists );
extern const char* gtk_about_dialog_get_version ( GtkAboutDialog* about );
extern void gtk_about_dialog_set_authors ( GtkAboutDialog* about, const char** authors );
extern void gtk_about_dialog_set_license ( GtkAboutDialog* about, const char* license );
extern void gtk_about_dialog_set_license_type ( GtkAboutDialog* about, GtkLicense license_type );
extern void gtk_about_dialog_set_copyright ( GtkAboutDialog* about, const char* copyright );
extern void gtk_about_dialog_set_documenters ( GtkAboutDialog* about, const char** documenters );
extern void gtk_about_dialog_set_logo ( GtkAboutDialog* about, GdkPaintable* logo );
extern void gtk_about_dialog_set_version ( GtkAboutDialog* about, const char* version );
extern void gtk_about_dialog_set_logo_icon_name ( GtkAboutDialog* about, const char* icon_name );
extern void gtk_about_dialog_set_translator_credits ( GtkAboutDialog* about, const char* translator_credits );
extern void gtk_about_dialog_set_system_information ( GtkAboutDialog* about, const char* system_information );
extern void gtk_about_dialog_set_wrap_license ( GtkAboutDialog* about, gboolean wrap_license );
extern void gtk_about_dialog_set_website_label ( GtkAboutDialog* about, const char* website_label );
extern void gtk_about_dialog_set_website ( GtkAboutDialog* about, const char* website );
extern void gtk_about_dialog_set_program_name ( GtkAboutDialog* about, const char* name );
