extern GtkWidget* gtk_entry_new ( void );
extern GtkWidget* gtk_entry_new_with_buffer ( GtkEntryBuffer* buffer );
extern float gtk_entry_get_alignment ( GtkEntry* entry );
extern gboolean gtk_entry_get_activates_default ( GtkEntry* entry );
extern int gtk_entry_get_current_icon_drag_source ( GtkEntry* entry );
extern GtkEntryBuffer* gtk_entry_get_buffer ( GtkEntry* entry );
extern PangoAttrList* gtk_entry_get_attributes ( GtkEntry* entry );
extern GMenuModel* gtk_entry_get_extra_menu ( GtkEntry* entry );
extern GtkEntryCompletion* gtk_entry_get_completion ( GtkEntry* entry );
extern gboolean gtk_entry_get_icon_activatable ( GtkEntry* entry, GtkEntryIconPosition icon_pos );
extern gboolean gtk_entry_get_has_frame ( GtkEntry* entry );
extern void gtk_entry_get_icon_area ( GtkEntry* entry, GtkEntryIconPosition icon_pos, GdkRectangle* icon_area );
extern GIcon* gtk_entry_get_icon_gicon ( GtkEntry* entry, GtkEntryIconPosition icon_pos );
extern const char* gtk_entry_get_icon_name ( GtkEntry* entry, GtkEntryIconPosition icon_pos );
extern int gtk_entry_get_icon_at_pos ( GtkEntry* entry, int x, int y );
extern GdkPaintable* gtk_entry_get_icon_paintable ( GtkEntry* entry, GtkEntryIconPosition icon_pos );
extern gboolean gtk_entry_get_icon_sensitive ( GtkEntry* entry, GtkEntryIconPosition icon_pos );
extern char* gtk_entry_get_icon_tooltip_markup ( GtkEntry* entry, GtkEntryIconPosition icon_pos );
extern GtkImageType gtk_entry_get_icon_storage_type ( GtkEntry* entry, GtkEntryIconPosition icon_pos );
extern char* gtk_entry_get_icon_tooltip_text ( GtkEntry* entry, GtkEntryIconPosition icon_pos );
extern GtkInputHints gtk_entry_get_input_hints ( GtkEntry* entry );
extern GtkInputPurpose gtk_entry_get_input_purpose ( GtkEntry* entry );
extern gboolean gtk_entry_get_overwrite_mode ( GtkEntry* entry );
extern gunichar gtk_entry_get_invisible_char ( GtkEntry* entry );
extern int gtk_entry_get_max_length ( GtkEntry* entry );
extern const char* gtk_entry_get_placeholder_text ( GtkEntry* entry );
extern double gtk_entry_get_progress_fraction ( GtkEntry* entry );
extern double gtk_entry_get_progress_pulse_step ( GtkEntry* entry );
extern PangoTabArray* gtk_entry_get_tabs ( GtkEntry* entry );
extern gboolean gtk_entry_grab_focus_without_selecting ( GtkEntry* entry );
extern guint16 gtk_entry_get_text_length ( GtkEntry* entry );
extern gboolean gtk_entry_get_visibility ( GtkEntry* entry );
extern void gtk_entry_reset_im_context ( GtkEntry* entry );
extern void gtk_entry_set_alignment ( GtkEntry* entry, float xalign );
extern void gtk_entry_progress_pulse ( GtkEntry* entry );
extern void gtk_entry_set_attributes ( GtkEntry* entry, PangoAttrList* attrs );
extern void gtk_entry_set_activates_default ( GtkEntry* entry, gboolean setting );
extern void gtk_entry_set_buffer ( GtkEntry* entry, GtkEntryBuffer* buffer );
extern void gtk_entry_set_has_frame ( GtkEntry* entry, gboolean setting );
extern void gtk_entry_set_completion ( GtkEntry* entry, GtkEntryCompletion* completion );
extern void gtk_entry_set_icon_activatable ( GtkEntry* entry, GtkEntryIconPosition icon_pos, gboolean activatable );
extern void gtk_entry_set_icon_drag_source ( GtkEntry* entry, GtkEntryIconPosition icon_pos, GdkContentProvider* provider, GdkDragAction actions );
extern void gtk_entry_set_icon_from_icon_name ( GtkEntry* entry, GtkEntryIconPosition icon_pos, const char* icon_name );
extern void gtk_entry_set_icon_from_gicon ( GtkEntry* entry, GtkEntryIconPosition icon_pos, GIcon* icon );
extern void gtk_entry_set_icon_sensitive ( GtkEntry* entry, GtkEntryIconPosition icon_pos, gboolean sensitive );
extern void gtk_entry_set_extra_menu ( GtkEntry* entry, GMenuModel* model );
extern void gtk_entry_set_icon_from_paintable ( GtkEntry* entry, GtkEntryIconPosition icon_pos, GdkPaintable* paintable );
extern void gtk_entry_set_icon_tooltip_text ( GtkEntry* entry, GtkEntryIconPosition icon_pos, const char* tooltip );
extern void gtk_entry_set_input_purpose ( GtkEntry* entry, GtkInputPurpose purpose );
extern void gtk_entry_set_max_length ( GtkEntry* entry, int max );
extern void gtk_entry_set_input_hints ( GtkEntry* entry, GtkInputHints hints );
extern void gtk_entry_set_invisible_char ( GtkEntry* entry, gunichar ch );
extern void gtk_entry_set_placeholder_text ( GtkEntry* entry, const char* text );
extern void gtk_entry_set_progress_fraction ( GtkEntry* entry, double fraction );
extern void gtk_entry_set_overwrite_mode ( GtkEntry* entry, gboolean overwrite );
extern void gtk_entry_set_icon_tooltip_markup ( GtkEntry* entry, GtkEntryIconPosition icon_pos, const char* tooltip );
extern void gtk_entry_set_progress_pulse_step ( GtkEntry* entry, double fraction );
extern void gtk_entry_set_tabs ( GtkEntry* entry, PangoTabArray* tabs );
extern void gtk_entry_set_visibility ( GtkEntry* entry, gboolean visible );
extern void gtk_entry_unset_invisible_char ( GtkEntry* entry );
