extern GtkPrintJob* gtk_print_job_new ( const char* title, GtkPrinter* printer, GtkPrintSettings* settings, GtkPageSetup* page_setup );
extern GtkNumberUpLayout gtk_print_job_get_n_up_layout ( GtkPrintJob* job );
extern gboolean gtk_print_job_get_collate ( GtkPrintJob* job );
extern guint gtk_print_job_get_n_up ( GtkPrintJob* job );
extern int gtk_print_job_get_num_copies ( GtkPrintJob* job );
extern GtkPrintPages gtk_print_job_get_pages ( GtkPrintJob* job );
extern GtkPageRange* gtk_print_job_get_page_ranges ( GtkPrintJob* job, int* n_ranges );
extern GtkPageSet gtk_print_job_get_page_set ( GtkPrintJob* job );
extern GtkPrinter* gtk_print_job_get_printer ( GtkPrintJob* job );
extern gboolean gtk_print_job_get_reverse ( GtkPrintJob* job );
extern double gtk_print_job_get_scale ( GtkPrintJob* job );
extern GtkPrintStatus gtk_print_job_get_status ( GtkPrintJob* job );
extern GtkPrintSettings* gtk_print_job_get_settings ( GtkPrintJob* job );
extern const char* gtk_print_job_get_title ( GtkPrintJob* job );
extern void gtk_print_job_send ( GtkPrintJob* job, GtkPrintJobCompleteFunc callback, gpointer user_data, GDestroyNotify dnotify );
extern cairo_surface_t* gtk_print_job_get_surface ( GtkPrintJob* job, GError** error );
extern gboolean gtk_print_job_get_track_print_status ( GtkPrintJob* job );
extern gboolean gtk_print_job_get_rotate ( GtkPrintJob* job );
extern void gtk_print_job_set_n_up ( GtkPrintJob* job, guint n_up );
extern void gtk_print_job_set_collate ( GtkPrintJob* job, gboolean collate );
extern void gtk_print_job_set_n_up_layout ( GtkPrintJob* job, GtkNumberUpLayout layout );
extern void gtk_print_job_set_page_set ( GtkPrintJob* job, GtkPageSet page_set );
extern void gtk_print_job_set_num_copies ( GtkPrintJob* job, int num_copies );
extern void gtk_print_job_set_page_ranges ( GtkPrintJob* job, GtkPageRange* ranges, int n_ranges );
extern void gtk_print_job_set_pages ( GtkPrintJob* job, GtkPrintPages pages );
extern void gtk_print_job_set_rotate ( GtkPrintJob* job, gboolean rotate );
extern void gtk_print_job_set_reverse ( GtkPrintJob* job, gboolean reverse );
extern void gtk_print_job_set_scale ( GtkPrintJob* job, double scale );
extern gboolean gtk_print_job_set_source_fd ( GtkPrintJob* job, int fd, GError** error );
extern gboolean gtk_print_job_set_source_file ( GtkPrintJob* job, const char* filename, GError** error );
extern void gtk_print_job_set_track_print_status ( GtkPrintJob* job, gboolean track_status );
