extern GtkWidget* gtk_button_new_with_label ( const char* label );
extern GtkWidget* gtk_button_new_with_mnemonic ( const char* label );
extern GtkWidget* gtk_button_new ( void );
extern GtkWidget* gtk_button_new_from_icon_name ( const char* icon_name );
extern gboolean gtk_button_get_use_underline ( GtkButton* button );
extern GtkWidget* gtk_button_get_child ( GtkButton* button );
extern gboolean gtk_button_get_has_frame ( GtkButton* button );
extern const char* gtk_button_get_icon_name ( GtkButton* button );
extern const char* gtk_button_get_label ( GtkButton* button );
extern void gtk_button_set_child ( GtkButton* button, GtkWidget* child );
extern void gtk_button_set_icon_name ( GtkButton* button, const char* icon_name );
extern void gtk_button_set_label ( GtkButton* button, const char* label );
extern void gtk_button_set_has_frame ( GtkButton* button, gboolean has_frame );
extern void gtk_button_set_use_underline ( GtkButton* button, gboolean use_underline );
