extern GList* gtk_gesture_get_group ( GtkGesture* gesture );
extern gboolean gtk_gesture_get_bounding_box_center ( GtkGesture* gesture, double* x, double* y );
extern GdkDevice* gtk_gesture_get_device ( GtkGesture* gesture );
extern gboolean gtk_gesture_get_bounding_box ( GtkGesture* gesture, GdkRectangle* rect );
extern GdkEventSequence* gtk_gesture_get_last_updated_sequence ( GtkGesture* gesture );
extern gboolean gtk_gesture_get_point ( GtkGesture* gesture, GdkEventSequence* sequence, double* x, double* y );
extern GList* gtk_gesture_get_sequences ( GtkGesture* gesture );
extern GdkEvent* gtk_gesture_get_last_event ( GtkGesture* gesture, GdkEventSequence* sequence );
extern void gtk_gesture_group ( GtkGesture* group_gesture, GtkGesture* gesture );
extern GtkEventSequenceState gtk_gesture_get_sequence_state ( GtkGesture* gesture, GdkEventSequence* sequence );
extern gboolean gtk_gesture_is_active ( GtkGesture* gesture );
extern gboolean gtk_gesture_is_grouped_with ( GtkGesture* gesture, GtkGesture* other );
extern gboolean gtk_gesture_handles_sequence ( GtkGesture* gesture, GdkEventSequence* sequence );
extern gboolean gtk_gesture_set_sequence_state ( GtkGesture* gesture, GdkEventSequence* sequence, GtkEventSequenceState state );
extern gboolean gtk_gesture_is_recognized ( GtkGesture* gesture );
extern void gtk_gesture_ungroup ( GtkGesture* gesture );
extern gboolean gtk_gesture_set_state ( GtkGesture* gesture, GtkEventSequenceState state );
