extern GtkPrintOperation* gtk_print_operation_new ( void );
extern GtkPageSetup* gtk_print_operation_get_default_page_setup ( GtkPrintOperation* op );
extern void gtk_print_operation_cancel ( GtkPrintOperation* op );
extern void gtk_print_operation_draw_page_finish ( GtkPrintOperation* op );
extern gboolean gtk_print_operation_get_embed_page_setup ( GtkPrintOperation* op );
extern gboolean gtk_print_operation_get_has_selection ( GtkPrintOperation* op );
extern void gtk_print_operation_get_error ( GtkPrintOperation* op, GError** error );
extern int gtk_print_operation_get_n_pages_to_print ( GtkPrintOperation* op );
extern GtkPrintSettings* gtk_print_operation_get_print_settings ( GtkPrintOperation* op );
extern gboolean gtk_print_operation_get_support_selection ( GtkPrintOperation* op );
extern GtkPrintStatus gtk_print_operation_get_status ( GtkPrintOperation* op );
extern gboolean gtk_print_operation_is_finished ( GtkPrintOperation* op );
extern const char* gtk_print_operation_get_status_string ( GtkPrintOperation* op );
extern void gtk_print_operation_set_current_page ( GtkPrintOperation* op, int current_page );
extern void gtk_print_operation_set_custom_tab_label ( GtkPrintOperation* op, const char* label );
extern GtkPrintOperationResult gtk_print_operation_run ( GtkPrintOperation* op, GtkPrintOperationAction action, GtkWindow* parent, GError** error );
extern void gtk_print_operation_set_allow_async ( GtkPrintOperation* op, gboolean allow_async );
extern void gtk_print_operation_set_embed_page_setup ( GtkPrintOperation* op, gboolean embed );
extern void gtk_print_operation_set_defer_drawing ( GtkPrintOperation* op );
extern void gtk_print_operation_set_default_page_setup ( GtkPrintOperation* op, GtkPageSetup* default_page_setup );
extern void gtk_print_operation_set_job_name ( GtkPrintOperation* op, const char* job_name );
extern void gtk_print_operation_set_export_filename ( GtkPrintOperation* op, const char* filename );
extern void gtk_print_operation_set_n_pages ( GtkPrintOperation* op, int n_pages );
extern void gtk_print_operation_set_has_selection ( GtkPrintOperation* op, gboolean has_selection );
extern void gtk_print_operation_set_print_settings ( GtkPrintOperation* op, GtkPrintSettings* print_settings );
extern void gtk_print_operation_set_track_print_status ( GtkPrintOperation* op, gboolean track_status );
extern void gtk_print_operation_set_show_progress ( GtkPrintOperation* op, gboolean show_progress );
extern void gtk_print_operation_set_support_selection ( GtkPrintOperation* op, gboolean support_selection );
extern void gtk_print_operation_set_use_full_page ( GtkPrintOperation* op, gboolean full_page );
extern void gtk_print_operation_set_unit ( GtkPrintOperation* op, GtkUnit unit );
