extern gboolean gtk_printer_accepts_pdf ( GtkPrinter* printer );
extern int gtk_printer_compare ( GtkPrinter* a, GtkPrinter* b );
extern gboolean gtk_printer_accepts_ps ( GtkPrinter* printer );
extern GtkPrinter* gtk_printer_new ( const char* name, GtkPrintBackend* backend, gboolean virtual_ );
extern GtkPageSetup* gtk_printer_get_default_page_size ( GtkPrinter* printer );
extern GtkPrintCapabilities gtk_printer_get_capabilities ( GtkPrinter* printer );
extern const char* gtk_printer_get_description ( GtkPrinter* printer );
extern GtkPrintBackend* gtk_printer_get_backend ( GtkPrinter* printer );
extern gboolean gtk_printer_get_hard_margins ( GtkPrinter* printer, double* top, double* bottom, double* left, double* right );
extern gboolean gtk_printer_get_hard_margins_for_paper_size ( GtkPrinter* printer, GtkPaperSize* paper_size, double* top, double* bottom, double* left, double* right );
extern const char* gtk_printer_get_location ( GtkPrinter* printer );
extern const char* gtk_printer_get_icon_name ( GtkPrinter* printer );
extern int gtk_printer_get_job_count ( GtkPrinter* printer );
extern const char* gtk_printer_get_state_message ( GtkPrinter* printer );
extern const char* gtk_printer_get_name ( GtkPrinter* printer );
extern gboolean gtk_printer_is_accepting_jobs ( GtkPrinter* printer );
extern gboolean gtk_printer_has_details ( GtkPrinter* printer );
extern gboolean gtk_printer_is_virtual ( GtkPrinter* printer );
extern gboolean gtk_printer_is_paused ( GtkPrinter* printer );
extern gboolean gtk_printer_is_default ( GtkPrinter* printer );
extern GList* gtk_printer_list_papers ( GtkPrinter* printer );
extern gboolean gtk_printer_is_active ( GtkPrinter* printer );
extern void gtk_printer_request_details ( GtkPrinter* printer );
