extern GtkWidget* gtk_image_new_from_icon_name ( const char* icon_name );
extern GtkWidget* gtk_image_new_from_file ( const char* filename );
extern GtkWidget* gtk_image_new ( void );
extern GtkWidget* gtk_image_new_from_paintable ( GdkPaintable* paintable );
extern GtkWidget* gtk_image_new_from_pixbuf ( GdkPixbuf* pixbuf );
extern void gtk_image_clear ( GtkImage* image );
extern GtkWidget* gtk_image_new_from_gicon ( GIcon* icon );
extern GtkWidget* gtk_image_new_from_resource ( const char* resource_path );
extern GIcon* gtk_image_get_gicon ( GtkImage* image );
extern GtkIconSize gtk_image_get_icon_size ( GtkImage* image );
extern const char* gtk_image_get_icon_name ( GtkImage* image );
extern GtkImageType gtk_image_get_storage_type ( GtkImage* image );
extern void gtk_image_set_from_file ( GtkImage* image, const char* filename );
extern void gtk_image_set_from_gicon ( GtkImage* image, GIcon* icon );
extern int gtk_image_get_pixel_size ( GtkImage* image );
extern GdkPaintable* gtk_image_get_paintable ( GtkImage* image );
extern void gtk_image_set_from_paintable ( GtkImage* image, GdkPaintable* paintable );
extern void gtk_image_set_from_icon_name ( GtkImage* image, const char* icon_name );
extern void gtk_image_set_from_pixbuf ( GtkImage* image, GdkPixbuf* pixbuf );
extern void gtk_image_set_from_resource ( GtkImage* image, const char* resource_path );
extern void gtk_image_set_icon_size ( GtkImage* image, GtkIconSize icon_size );
extern void gtk_image_set_pixel_size ( GtkImage* image, int pixel_size );
