extern void gtk_assistant_add_action_widget ( GtkAssistant* assistant, GtkWidget* child );
extern void gtk_assistant_commit ( GtkAssistant* assistant );
extern GtkWidget* gtk_assistant_new ( void );
extern int gtk_assistant_append_page ( GtkAssistant* assistant, GtkWidget* page );
extern int gtk_assistant_get_current_page ( GtkAssistant* assistant );
extern int gtk_assistant_get_n_pages ( GtkAssistant* assistant );
extern GtkAssistantPage* gtk_assistant_get_page ( GtkAssistant* assistant, GtkWidget* child );
extern gboolean gtk_assistant_get_page_complete ( GtkAssistant* assistant, GtkWidget* page );
extern GtkWidget* gtk_assistant_get_nth_page ( GtkAssistant* assistant, int page_num );
extern const char* gtk_assistant_get_page_title ( GtkAssistant* assistant, GtkWidget* page );
extern int gtk_assistant_prepend_page ( GtkAssistant* assistant, GtkWidget* page );
extern GtkAssistantPageType gtk_assistant_get_page_type ( GtkAssistant* assistant, GtkWidget* page );
extern GListModel* gtk_assistant_get_pages ( GtkAssistant* assistant );
extern void gtk_assistant_next_page ( GtkAssistant* assistant );
extern int gtk_assistant_insert_page ( GtkAssistant* assistant, GtkWidget* page, int position );
extern void gtk_assistant_previous_page ( GtkAssistant* assistant );
extern void gtk_assistant_set_forward_page_func ( GtkAssistant* assistant, GtkAssistantPageFunc page_func, gpointer data, GDestroyNotify destroy );
extern void gtk_assistant_remove_action_widget ( GtkAssistant* assistant, GtkWidget* child );
extern void gtk_assistant_set_current_page ( GtkAssistant* assistant, int page_num );
extern void gtk_assistant_remove_page ( GtkAssistant* assistant, int page_num );
extern void gtk_assistant_set_page_type ( GtkAssistant* assistant, GtkWidget* page, GtkAssistantPageType type );
extern void gtk_assistant_set_page_complete ( GtkAssistant* assistant, GtkWidget* page, gboolean complete );
extern void gtk_assistant_set_page_title ( GtkAssistant* assistant, GtkWidget* page, const char* title );
extern void gtk_assistant_update_buttons_state ( GtkAssistant* assistant );
