extern gboolean gtk_tree_model_filter_convert_child_iter_to_iter ( GtkTreeModelFilter* filter, GtkTreeIter* filter_iter, GtkTreeIter* child_iter );
extern void gtk_tree_model_filter_convert_iter_to_child_iter ( GtkTreeModelFilter* filter, GtkTreeIter* child_iter, GtkTreeIter* filter_iter );
extern GtkTreePath* gtk_tree_model_filter_convert_child_path_to_path ( GtkTreeModelFilter* filter, GtkTreePath* child_path );
extern void gtk_tree_model_filter_clear_cache ( GtkTreeModelFilter* filter );
extern GtkTreeModel* gtk_tree_model_filter_get_model ( GtkTreeModelFilter* filter );
extern GtkTreePath* gtk_tree_model_filter_convert_path_to_child_path ( GtkTreeModelFilter* filter, GtkTreePath* filter_path );
extern void gtk_tree_model_filter_set_visible_column ( GtkTreeModelFilter* filter, int column );
extern void gtk_tree_model_filter_refilter ( GtkTreeModelFilter* filter );
extern void gtk_tree_model_filter_set_visible_func ( GtkTreeModelFilter* filter, GtkTreeModelFilterVisibleFunc func, gpointer data, GDestroyNotify destroy );
extern void gtk_tree_model_filter_set_modify_func ( GtkTreeModelFilter* filter, int n_columns, GType* types, GtkTreeModelFilterModifyFunc func, gpointer data, GDestroyNotify destroy );
