extern cairo_t* gtk_print_context_get_cairo_context ( GtkPrintContext* context );
extern PangoLayout* gtk_print_context_create_pango_layout ( GtkPrintContext* context );
extern PangoContext* gtk_print_context_create_pango_context ( GtkPrintContext* context );
extern double gtk_print_context_get_dpi_y ( GtkPrintContext* context );
extern gboolean gtk_print_context_get_hard_margins ( GtkPrintContext* context, double* top, double* bottom, double* left, double* right );
extern double gtk_print_context_get_height ( GtkPrintContext* context );
extern double gtk_print_context_get_dpi_x ( GtkPrintContext* context );
extern GtkPageSetup* gtk_print_context_get_page_setup ( GtkPrintContext* context );
extern double gtk_print_context_get_width ( GtkPrintContext* context );
extern void gtk_print_context_set_cairo_context ( GtkPrintContext* context, cairo_t* cr, double dpi_x, double dpi_y );
extern PangoFontMap* gtk_print_context_get_pango_fontmap ( GtkPrintContext* context );
