extern GtkWidget* gtk_notebook_new ( void );
extern void gtk_notebook_detach_tab ( GtkNotebook* notebook, GtkWidget* child );
extern int gtk_notebook_append_page_menu ( GtkNotebook* notebook, GtkWidget* child, GtkWidget* tab_label, GtkWidget* menu_label );
extern int gtk_notebook_append_page ( GtkNotebook* notebook, GtkWidget* child, GtkWidget* tab_label );
extern const char* gtk_notebook_get_group_name ( GtkNotebook* notebook );
extern int gtk_notebook_get_current_page ( GtkNotebook* notebook );
extern GtkWidget* gtk_notebook_get_menu_label ( GtkNotebook* notebook, GtkWidget* child );
extern const char* gtk_notebook_get_menu_label_text ( GtkNotebook* notebook, GtkWidget* child );
extern int gtk_notebook_get_n_pages ( GtkNotebook* notebook );
extern GtkWidget* gtk_notebook_get_nth_page ( GtkNotebook* notebook, int page_num );
extern GtkNotebookPage* gtk_notebook_get_page ( GtkNotebook* notebook, GtkWidget* child );
extern GtkWidget* gtk_notebook_get_action_widget ( GtkNotebook* notebook, GtkPackType pack_type );
extern gboolean gtk_notebook_get_show_tabs ( GtkNotebook* notebook );
extern gboolean gtk_notebook_get_scrollable ( GtkNotebook* notebook );
extern GListModel* gtk_notebook_get_pages ( GtkNotebook* notebook );
extern gboolean gtk_notebook_get_show_border ( GtkNotebook* notebook );
extern gboolean gtk_notebook_get_tab_detachable ( GtkNotebook* notebook, GtkWidget* child );
extern GtkWidget* gtk_notebook_get_tab_label ( GtkNotebook* notebook, GtkWidget* child );
extern int gtk_notebook_insert_page ( GtkNotebook* notebook, GtkWidget* child, GtkWidget* tab_label, int position );
extern int gtk_notebook_insert_page_menu ( GtkNotebook* notebook, GtkWidget* child, GtkWidget* tab_label, GtkWidget* menu_label, int position );
extern const char* gtk_notebook_get_tab_label_text ( GtkNotebook* notebook, GtkWidget* child );
extern gboolean gtk_notebook_get_tab_reorderable ( GtkNotebook* notebook, GtkWidget* child );
extern GtkPositionType gtk_notebook_get_tab_pos ( GtkNotebook* notebook );
extern void gtk_notebook_popup_enable ( GtkNotebook* notebook );
extern void gtk_notebook_next_page ( GtkNotebook* notebook );
extern int gtk_notebook_prepend_page ( GtkNotebook* notebook, GtkWidget* child, GtkWidget* tab_label );
extern void gtk_notebook_popup_disable ( GtkNotebook* notebook );
extern int gtk_notebook_prepend_page_menu ( GtkNotebook* notebook, GtkWidget* child, GtkWidget* tab_label, GtkWidget* menu_label );
extern int gtk_notebook_page_num ( GtkNotebook* notebook, GtkWidget* child );
extern void gtk_notebook_prev_page ( GtkNotebook* notebook );
extern void gtk_notebook_set_action_widget ( GtkNotebook* notebook, GtkWidget* widget, GtkPackType pack_type );
extern void gtk_notebook_set_menu_label ( GtkNotebook* notebook, GtkWidget* child, GtkWidget* menu_label );
extern void gtk_notebook_remove_page ( GtkNotebook* notebook, int page_num );
extern void gtk_notebook_reorder_child ( GtkNotebook* notebook, GtkWidget* child, int position );
extern void gtk_notebook_set_group_name ( GtkNotebook* notebook, const char* group_name );
extern void gtk_notebook_set_scrollable ( GtkNotebook* notebook, gboolean scrollable );
extern void gtk_notebook_set_show_tabs ( GtkNotebook* notebook, gboolean show_tabs );
extern void gtk_notebook_set_show_border ( GtkNotebook* notebook, gboolean show_border );
extern void gtk_notebook_set_current_page ( GtkNotebook* notebook, int page_num );
extern void gtk_notebook_set_menu_label_text ( GtkNotebook* notebook, GtkWidget* child, const char* menu_text );
extern void gtk_notebook_set_tab_detachable ( GtkNotebook* notebook, GtkWidget* child, gboolean detachable );
extern void gtk_notebook_set_tab_pos ( GtkNotebook* notebook, GtkPositionType pos );
extern void gtk_notebook_set_tab_label ( GtkNotebook* notebook, GtkWidget* child, GtkWidget* tab_label );
extern void gtk_notebook_set_tab_reorderable ( GtkNotebook* notebook, GtkWidget* child, gboolean reorderable );
extern void gtk_notebook_set_tab_label_text ( GtkNotebook* notebook, GtkWidget* child, const char* tab_text );
