extern gboolean gtk_app_chooser_widget_get_show_default ( GtkAppChooserWidget* self );
extern gboolean gtk_app_chooser_widget_get_show_fallback ( GtkAppChooserWidget* self );
extern GtkWidget* gtk_app_chooser_widget_new ( const char* content_type );
extern gboolean gtk_app_chooser_widget_get_show_other ( GtkAppChooserWidget* self );
extern const char* gtk_app_chooser_widget_get_default_text ( GtkAppChooserWidget* self );
extern gboolean gtk_app_chooser_widget_get_show_all ( GtkAppChooserWidget* self );
extern void gtk_app_chooser_widget_set_default_text ( GtkAppChooserWidget* self, const char* text );
extern gboolean gtk_app_chooser_widget_get_show_recommended ( GtkAppChooserWidget* self );
extern void gtk_app_chooser_widget_set_show_fallback ( GtkAppChooserWidget* self, gboolean setting );
extern void gtk_app_chooser_widget_set_show_default ( GtkAppChooserWidget* self, gboolean setting );
extern void gtk_app_chooser_widget_set_show_other ( GtkAppChooserWidget* self, gboolean setting );
extern void gtk_app_chooser_widget_set_show_all ( GtkAppChooserWidget* self, gboolean setting );
extern void gtk_app_chooser_widget_set_show_recommended ( GtkAppChooserWidget* self, gboolean setting );
