extern GtkWidget* gtk_window_new ( void );
extern void gtk_window_destroy ( GtkWindow* window );
extern void gtk_window_fullscreen ( GtkWindow* window );
extern void gtk_window_close ( GtkWindow* window );
extern gboolean gtk_window_get_decorated ( GtkWindow* window );
extern void gtk_window_get_default_size ( GtkWindow* window, int* width, int* height );
extern void gtk_window_fullscreen_on_monitor ( GtkWindow* window, GdkMonitor* monitor );
extern GtkWidget* gtk_window_get_child ( GtkWindow* window );
extern GtkWidget* gtk_window_get_default_widget ( GtkWindow* window );
extern GtkApplication* gtk_window_get_application ( GtkWindow* window );
extern GtkWidget* gtk_window_get_focus ( GtkWindow* window );
extern gboolean gtk_window_get_destroy_with_parent ( GtkWindow* window );
extern gboolean gtk_window_get_deletable ( GtkWindow* window );
extern GtkWindowGroup* gtk_window_get_group ( GtkWindow* window );
extern gboolean gtk_window_get_hide_on_close ( GtkWindow* window );
extern gboolean gtk_window_get_handle_menubar_accel ( GtkWindow* window );
extern gboolean gtk_window_get_focus_visible ( GtkWindow* window );
extern const char* gtk_window_get_icon_name ( GtkWindow* window );
extern gboolean gtk_window_get_mnemonics_visible ( GtkWindow* window );
extern gboolean gtk_window_get_modal ( GtkWindow* window );
extern const char* gtk_window_get_title ( GtkWindow* window );
extern GtkWidget* gtk_window_get_titlebar ( GtkWindow* window );
extern gboolean gtk_window_get_resizable ( GtkWindow* window );
extern gboolean gtk_window_has_group ( GtkWindow* window );
extern GtkWindow* gtk_window_get_transient_for ( GtkWindow* window );
extern gboolean gtk_window_is_active ( GtkWindow* window );
extern void gtk_window_maximize ( GtkWindow* window );
extern gboolean gtk_window_is_fullscreen ( GtkWindow* window );
extern gboolean gtk_window_is_maximized ( GtkWindow* window );
extern void gtk_window_minimize ( GtkWindow* window );
extern void gtk_window_present ( GtkWindow* window );
extern void gtk_window_set_decorated ( GtkWindow* window, gboolean setting );
extern void gtk_window_present_with_time ( GtkWindow* window, guint32 timestamp );
extern void gtk_window_set_child ( GtkWindow* window, GtkWidget* child );
extern void gtk_window_set_application ( GtkWindow* window, GtkApplication* application );
extern void gtk_window_set_default_size ( GtkWindow* window, int width, int height );
extern void gtk_window_set_default_widget ( GtkWindow* window, GtkWidget* default_widget );
extern void gtk_window_set_focus ( GtkWindow* window, GtkWidget* focus );
extern void gtk_window_set_deletable ( GtkWindow* window, gboolean setting );
extern void gtk_window_set_display ( GtkWindow* window, GdkDisplay* display );
extern void gtk_window_set_destroy_with_parent ( GtkWindow* window, gboolean setting );
extern void gtk_window_set_focus_visible ( GtkWindow* window, gboolean setting );
extern void gtk_window_set_handle_menubar_accel ( GtkWindow* window, gboolean handle_menubar_accel );
extern void gtk_window_set_hide_on_close ( GtkWindow* window, gboolean setting );
extern void gtk_window_set_icon_name ( GtkWindow* window, const char* name );
extern void gtk_window_set_modal ( GtkWindow* window, gboolean modal );
extern void gtk_window_set_title ( GtkWindow* window, const char* title );
extern void gtk_window_set_mnemonics_visible ( GtkWindow* window, gboolean setting );
extern void gtk_window_set_startup_id ( GtkWindow* window, const char* startup_id );
extern void gtk_window_set_resizable ( GtkWindow* window, gboolean resizable );
extern void gtk_window_set_titlebar ( GtkWindow* window, GtkWidget* titlebar );
extern void gtk_window_unmaximize ( GtkWindow* window );
extern void gtk_window_unfullscreen ( GtkWindow* window );
extern void gtk_window_unminimize ( GtkWindow* window );
extern void gtk_window_set_transient_for ( GtkWindow* window, GtkWindow* parent );
extern GListModel* gtk_window_get_toplevels (void);
