extern void gtk_tree_store_append ( GtkTreeStore* tree_store, GtkTreeIter* iter, GtkTreeIter* parent );
extern void gtk_tree_store_clear ( GtkTreeStore* tree_store );
extern GtkTreeStore* gtk_tree_store_newv ( int n_columns, GType* types );
extern GtkTreeStore* gtk_tree_store_new ( int n_columns, ... );
extern void gtk_tree_store_insert_before ( GtkTreeStore* tree_store, GtkTreeIter* iter, GtkTreeIter* parent, GtkTreeIter* sibling );
extern void gtk_tree_store_insert_after ( GtkTreeStore* tree_store, GtkTreeIter* iter, GtkTreeIter* parent, GtkTreeIter* sibling );
extern void gtk_tree_store_insert_with_valuesv ( GtkTreeStore* tree_store, GtkTreeIter* iter, GtkTreeIter* parent, int position, int* columns, GValue* values, int n_values );
extern void gtk_tree_store_insert_with_values ( GtkTreeStore* tree_store, GtkTreeIter* iter, GtkTreeIter* parent, int position, ... );
extern void gtk_tree_store_insert ( GtkTreeStore* tree_store, GtkTreeIter* iter, GtkTreeIter* parent, int position );
extern gboolean gtk_tree_store_is_ancestor ( GtkTreeStore* tree_store, GtkTreeIter* iter, GtkTreeIter* descendant );
extern gboolean gtk_tree_store_iter_is_valid ( GtkTreeStore* tree_store, GtkTreeIter* iter );
extern void gtk_tree_store_move_before ( GtkTreeStore* tree_store, GtkTreeIter* iter, GtkTreeIter* position );
extern void gtk_tree_store_move_after ( GtkTreeStore* tree_store, GtkTreeIter* iter, GtkTreeIter* position );
extern void gtk_tree_store_prepend ( GtkTreeStore* tree_store, GtkTreeIter* iter, GtkTreeIter* parent );
extern int gtk_tree_store_iter_depth ( GtkTreeStore* tree_store, GtkTreeIter* iter );
extern gboolean gtk_tree_store_remove ( GtkTreeStore* tree_store, GtkTreeIter* iter );
extern void gtk_tree_store_reorder ( GtkTreeStore* tree_store, GtkTreeIter* parent, int* new_order );
extern void gtk_tree_store_set_value ( GtkTreeStore* tree_store, GtkTreeIter* iter, int column, GValue* value );
extern void gtk_tree_store_set_valist ( GtkTreeStore* tree_store, GtkTreeIter* iter, va_list var_args );
extern void gtk_tree_store_set_column_types ( GtkTreeStore* tree_store, int n_columns, GType* types );
extern void gtk_tree_store_set ( GtkTreeStore* tree_store, GtkTreeIter* iter, ... );
extern void gtk_tree_store_set_valuesv ( GtkTreeStore* tree_store, GtkTreeIter* iter, int* columns, GValue* values, int n_values );
extern void gtk_tree_store_swap ( GtkTreeStore* tree_store, GtkTreeIter* a, GtkTreeIter* b );
