extern void gtk_cell_renderer_get_alignment ( GtkCellRenderer* cell, float* xalign, float* yalign );
extern gboolean gtk_cell_renderer_activate ( GtkCellRenderer* cell, GdkEvent* event, GtkWidget* widget, const char* path, const GdkRectangle* background_area, const GdkRectangle* cell_area, GtkCellRendererState flags );
extern void gtk_cell_renderer_get_fixed_size ( GtkCellRenderer* cell, int* width, int* height );
extern void gtk_cell_renderer_get_aligned_area ( GtkCellRenderer* cell, GtkWidget* widget, GtkCellRendererState flags, const GdkRectangle* cell_area, GdkRectangle* aligned_area );
extern gboolean gtk_cell_renderer_get_is_expander ( GtkCellRenderer* cell );
extern void gtk_cell_renderer_get_preferred_height_for_width ( GtkCellRenderer* cell, GtkWidget* widget, int width, int* minimum_height, int* natural_height );
extern gboolean gtk_cell_renderer_get_is_expanded ( GtkCellRenderer* cell );
extern void gtk_cell_renderer_get_preferred_height ( GtkCellRenderer* cell, GtkWidget* widget, int* minimum_size, int* natural_size );
extern void gtk_cell_renderer_get_preferred_size ( GtkCellRenderer* cell, GtkWidget* widget, GtkRequisition* minimum_size, GtkRequisition* natural_size );
extern void gtk_cell_renderer_get_padding ( GtkCellRenderer* cell, int* xpad, int* ypad );
extern void gtk_cell_renderer_get_preferred_width ( GtkCellRenderer* cell, GtkWidget* widget, int* minimum_size, int* natural_size );
extern void gtk_cell_renderer_get_preferred_width_for_height ( GtkCellRenderer* cell, GtkWidget* widget, int height, int* minimum_width, int* natural_width );
extern GtkStateFlags gtk_cell_renderer_get_state ( GtkCellRenderer* cell, GtkWidget* widget, GtkCellRendererState cell_state );
extern gboolean gtk_cell_renderer_get_sensitive ( GtkCellRenderer* cell );
extern GtkSizeRequestMode gtk_cell_renderer_get_request_mode ( GtkCellRenderer* cell );
extern gboolean gtk_cell_renderer_is_activatable ( GtkCellRenderer* cell );
extern gboolean gtk_cell_renderer_get_visible ( GtkCellRenderer* cell );
extern void gtk_cell_renderer_set_fixed_size ( GtkCellRenderer* cell, int width, int height );
extern void gtk_cell_renderer_set_is_expander ( GtkCellRenderer* cell, gboolean is_expander );
extern void gtk_cell_renderer_set_is_expanded ( GtkCellRenderer* cell, gboolean is_expanded );
extern void gtk_cell_renderer_set_padding ( GtkCellRenderer* cell, int xpad, int ypad );
extern void gtk_cell_renderer_set_alignment ( GtkCellRenderer* cell, float xalign, float yalign );
extern void gtk_cell_renderer_set_sensitive ( GtkCellRenderer* cell, gboolean sensitive );
extern void gtk_cell_renderer_stop_editing ( GtkCellRenderer* cell, gboolean canceled );
extern void gtk_cell_renderer_snapshot ( GtkCellRenderer* cell, GtkSnapshot* snapshot, GtkWidget* widget, const GdkRectangle* background_area, const GdkRectangle* cell_area, GtkCellRendererState flags );
extern void gtk_cell_renderer_set_visible ( GtkCellRenderer* cell, gboolean visible );
extern GtkCellEditable* gtk_cell_renderer_start_editing ( GtkCellRenderer* cell, GdkEvent* event, GtkWidget* widget, const char* path, const GdkRectangle* background_area, const GdkRectangle* cell_area, GtkCellRendererState flags );
