extern GtkTreeViewColumn* gtk_tree_view_column_new ( void );
extern void gtk_tree_view_column_add_attribute ( GtkTreeViewColumn* tree_column, GtkCellRenderer* cell_renderer, const char* attribute, int column );
extern GtkTreeViewColumn* gtk_tree_view_column_new_with_attributes ( const char* title, GtkCellRenderer* cell, ... );
extern GtkTreeViewColumn* gtk_tree_view_column_new_with_area ( GtkCellArea* area );
extern void gtk_tree_view_column_cell_get_size ( GtkTreeViewColumn* tree_column, int* x_offset, int* y_offset, int* width, int* height );
extern gboolean gtk_tree_view_column_cell_is_visible ( GtkTreeViewColumn* tree_column );
extern gboolean gtk_tree_view_column_cell_get_position ( GtkTreeViewColumn* tree_column, GtkCellRenderer* cell_renderer, int* x_offset, int* width );
extern void gtk_tree_view_column_clear ( GtkTreeViewColumn* tree_column );
extern void gtk_tree_view_column_cell_set_cell_data ( GtkTreeViewColumn* tree_column, GtkTreeModel* tree_model, GtkTreeIter* iter, gboolean is_expander, gboolean is_expanded );
extern void gtk_tree_view_column_clear_attributes ( GtkTreeViewColumn* tree_column, GtkCellRenderer* cell_renderer );
extern gboolean gtk_tree_view_column_get_clickable ( GtkTreeViewColumn* tree_column );
extern void gtk_tree_view_column_focus_cell ( GtkTreeViewColumn* tree_column, GtkCellRenderer* cell );
extern float gtk_tree_view_column_get_alignment ( GtkTreeViewColumn* tree_column );
extern GtkWidget* gtk_tree_view_column_get_button ( GtkTreeViewColumn* tree_column );
extern void gtk_tree_view_column_clicked ( GtkTreeViewColumn* tree_column );
extern int gtk_tree_view_column_get_max_width ( GtkTreeViewColumn* tree_column );
extern int gtk_tree_view_column_get_fixed_width ( GtkTreeViewColumn* tree_column );
extern gboolean gtk_tree_view_column_get_expand ( GtkTreeViewColumn* tree_column );
extern gboolean gtk_tree_view_column_get_reorderable ( GtkTreeViewColumn* tree_column );
extern GtkTreeViewColumnSizing gtk_tree_view_column_get_sizing ( GtkTreeViewColumn* tree_column );
extern int gtk_tree_view_column_get_min_width ( GtkTreeViewColumn* tree_column );
extern gboolean gtk_tree_view_column_get_resizable ( GtkTreeViewColumn* tree_column );
extern int gtk_tree_view_column_get_sort_column_id ( GtkTreeViewColumn* tree_column );
extern int gtk_tree_view_column_get_spacing ( GtkTreeViewColumn* tree_column );
extern gboolean gtk_tree_view_column_get_sort_indicator ( GtkTreeViewColumn* tree_column );
extern GtkSortType gtk_tree_view_column_get_sort_order ( GtkTreeViewColumn* tree_column );
extern GtkWidget* gtk_tree_view_column_get_tree_view ( GtkTreeViewColumn* tree_column );
extern const char* gtk_tree_view_column_get_title ( GtkTreeViewColumn* tree_column );
extern gboolean gtk_tree_view_column_get_visible ( GtkTreeViewColumn* tree_column );
extern GtkWidget* gtk_tree_view_column_get_widget ( GtkTreeViewColumn* tree_column );
extern int gtk_tree_view_column_get_width ( GtkTreeViewColumn* tree_column );
extern int gtk_tree_view_column_get_x_offset ( GtkTreeViewColumn* tree_column );
extern void gtk_tree_view_column_pack_start ( GtkTreeViewColumn* tree_column, GtkCellRenderer* cell, gboolean expand );
extern void gtk_tree_view_column_pack_end ( GtkTreeViewColumn* tree_column, GtkCellRenderer* cell, gboolean expand );
extern void gtk_tree_view_column_set_alignment ( GtkTreeViewColumn* tree_column, float xalign );
extern void gtk_tree_view_column_set_attributes ( GtkTreeViewColumn* tree_column, GtkCellRenderer* cell_renderer, ... );
extern void gtk_tree_view_column_queue_resize ( GtkTreeViewColumn* tree_column );
extern void gtk_tree_view_column_set_clickable ( GtkTreeViewColumn* tree_column, gboolean clickable );
extern void gtk_tree_view_column_set_fixed_width ( GtkTreeViewColumn* tree_column, int fixed_width );
extern void gtk_tree_view_column_set_expand ( GtkTreeViewColumn* tree_column, gboolean expand );
extern void gtk_tree_view_column_set_cell_data_func ( GtkTreeViewColumn* tree_column, GtkCellRenderer* cell_renderer, GtkTreeCellDataFunc func, gpointer func_data, GDestroyNotify destroy );
extern void gtk_tree_view_column_set_min_width ( GtkTreeViewColumn* tree_column, int min_width );
extern void gtk_tree_view_column_set_max_width ( GtkTreeViewColumn* tree_column, int max_width );
extern void gtk_tree_view_column_set_resizable ( GtkTreeViewColumn* tree_column, gboolean resizable );
extern void gtk_tree_view_column_set_sizing ( GtkTreeViewColumn* tree_column, GtkTreeViewColumnSizing type );
extern void gtk_tree_view_column_set_sort_column_id ( GtkTreeViewColumn* tree_column, int sort_column_id );
extern void gtk_tree_view_column_set_sort_indicator ( GtkTreeViewColumn* tree_column, gboolean setting );
extern void gtk_tree_view_column_set_reorderable ( GtkTreeViewColumn* tree_column, gboolean reorderable );
extern void gtk_tree_view_column_set_spacing ( GtkTreeViewColumn* tree_column, int spacing );
extern void gtk_tree_view_column_set_sort_order ( GtkTreeViewColumn* tree_column, GtkSortType order );
extern void gtk_tree_view_column_set_title ( GtkTreeViewColumn* tree_column, const char* title );
extern void gtk_tree_view_column_set_widget ( GtkTreeViewColumn* tree_column, GtkWidget* widget );
extern void gtk_tree_view_column_set_visible ( GtkTreeViewColumn* tree_column, gboolean visible );
