extern GtkWidget* gtk_combo_box_new_with_model ( GtkTreeModel* model );
extern GtkWidget* gtk_combo_box_new_with_model_and_entry ( GtkTreeModel* model );
extern GtkWidget* gtk_combo_box_new_with_entry ( void );
extern GtkWidget* gtk_combo_box_new ( void );
extern const char* gtk_combo_box_get_active_id ( GtkComboBox* combo_box );
extern gboolean gtk_combo_box_get_active_iter ( GtkComboBox* combo_box, GtkTreeIter* iter );
extern GtkWidget* gtk_combo_box_get_child ( GtkComboBox* combo_box );
extern int gtk_combo_box_get_active ( GtkComboBox* combo_box );
extern GtkSensitivityType gtk_combo_box_get_button_sensitivity ( GtkComboBox* combo_box );
extern int gtk_combo_box_get_entry_text_column ( GtkComboBox* combo_box );
extern gboolean gtk_combo_box_get_has_entry ( GtkComboBox* combo_box );
extern GtkTreeModel* gtk_combo_box_get_model ( GtkComboBox* combo_box );
extern int gtk_combo_box_get_id_column ( GtkComboBox* combo_box );
extern gboolean gtk_combo_box_get_popup_fixed_width ( GtkComboBox* combo_box );
extern void gtk_combo_box_popup ( GtkComboBox* combo_box );
extern void gtk_combo_box_popdown ( GtkComboBox* combo_box );
extern GtkTreeViewRowSeparatorFunc gtk_combo_box_get_row_separator_func ( GtkComboBox* combo_box );
extern void gtk_combo_box_set_active ( GtkComboBox* combo_box, int index_ );
extern void gtk_combo_box_popup_for_device ( GtkComboBox* combo_box, GdkDevice* device );
extern gboolean gtk_combo_box_set_active_id ( GtkComboBox* combo_box, const char* active_id );
extern void gtk_combo_box_set_child ( GtkComboBox* combo_box, GtkWidget* child );
extern void gtk_combo_box_set_entry_text_column ( GtkComboBox* combo_box, int text_column );
extern void gtk_combo_box_set_button_sensitivity ( GtkComboBox* combo_box, GtkSensitivityType sensitivity );
extern void gtk_combo_box_set_active_iter ( GtkComboBox* combo_box, GtkTreeIter* iter );
extern void gtk_combo_box_set_id_column ( GtkComboBox* combo_box, int id_column );
extern void gtk_combo_box_set_model ( GtkComboBox* combo_box, GtkTreeModel* model );
extern void gtk_combo_box_set_row_separator_func ( GtkComboBox* combo_box, GtkTreeViewRowSeparatorFunc func, gpointer data, GDestroyNotify destroy );
extern void gtk_combo_box_set_popup_fixed_width ( GtkComboBox* combo_box, gboolean fixed );
