extern GtkWidget* gtk_column_view_new ( GtkSelectionModel* model );
extern gboolean gtk_column_view_get_enable_rubberband ( GtkColumnView* self );
extern gboolean gtk_column_view_get_show_column_separators ( GtkColumnView* self );
extern GListModel* gtk_column_view_get_columns ( GtkColumnView* self );
extern void gtk_column_view_append_column ( GtkColumnView* self, GtkColumnViewColumn* column );
extern gboolean gtk_column_view_get_show_row_separators ( GtkColumnView* self );
extern gboolean gtk_column_view_get_reorderable ( GtkColumnView* self );
extern GtkSorter* gtk_column_view_get_sorter ( GtkColumnView* self );
extern gboolean gtk_column_view_get_single_click_activate ( GtkColumnView* self );
extern void gtk_column_view_insert_column ( GtkColumnView* self, guint position, GtkColumnViewColumn* column );
extern void gtk_column_view_set_enable_rubberband ( GtkColumnView* self, gboolean enable_rubberband );
extern void gtk_column_view_remove_column ( GtkColumnView* self, GtkColumnViewColumn* column );
extern GtkSelectionModel* gtk_column_view_get_model ( GtkColumnView* self );
extern void gtk_column_view_set_model ( GtkColumnView* self, GtkSelectionModel* model );
extern void gtk_column_view_set_show_row_separators ( GtkColumnView* self, gboolean show_row_separators );
extern void gtk_column_view_set_show_column_separators ( GtkColumnView* self, gboolean show_column_separators );
extern void gtk_column_view_set_reorderable ( GtkColumnView* self, gboolean reorderable );
extern void gtk_column_view_set_single_click_activate ( GtkColumnView* self, gboolean single_click_activate );
extern void gtk_column_view_sort_by_column ( GtkColumnView* self, GtkColumnViewColumn* column, GtkSortType direction );
