extern void gtk_media_stream_error ( GtkMediaStream* self, GQuark domain, int code, const char* format, ... );
extern void gtk_media_stream_gerror ( GtkMediaStream* self, GError* error );
extern void gtk_media_stream_ended ( GtkMediaStream* self );
extern const GError* gtk_media_stream_get_error ( GtkMediaStream* self );
extern void gtk_media_stream_error_valist ( GtkMediaStream* self, GQuark domain, int code, const char* format, va_list args );
extern gboolean gtk_media_stream_get_ended ( GtkMediaStream* self );
extern gboolean gtk_media_stream_get_loop ( GtkMediaStream* self );
extern gboolean gtk_media_stream_get_playing ( GtkMediaStream* self );
extern gboolean gtk_media_stream_get_muted ( GtkMediaStream* self );
extern gint64 gtk_media_stream_get_timestamp ( GtkMediaStream* self );
extern gint64 gtk_media_stream_get_duration ( GtkMediaStream* self );
extern double gtk_media_stream_get_volume ( GtkMediaStream* self );
extern gboolean gtk_media_stream_is_prepared ( GtkMediaStream* self );
extern gboolean gtk_media_stream_has_video ( GtkMediaStream* self );
extern gboolean gtk_media_stream_is_seekable ( GtkMediaStream* self );
extern gboolean gtk_media_stream_is_seeking ( GtkMediaStream* self );
extern void gtk_media_stream_play ( GtkMediaStream* self );
extern void gtk_media_stream_prepared ( GtkMediaStream* self, gboolean has_audio, gboolean has_video, gboolean seekable, gint64 duration );
extern void gtk_media_stream_pause ( GtkMediaStream* self );
extern void gtk_media_stream_seek_failed ( GtkMediaStream* self );
extern void gtk_media_stream_realize ( GtkMediaStream* self, GdkSurface* surface );
extern void gtk_media_stream_seek ( GtkMediaStream* self, gint64 timestamp );
extern void gtk_media_stream_set_muted ( GtkMediaStream* self, gboolean muted );
extern gboolean gtk_media_stream_has_audio ( GtkMediaStream* self );
extern void gtk_media_stream_set_playing ( GtkMediaStream* self, gboolean playing );
extern void gtk_media_stream_set_loop ( GtkMediaStream* self, gboolean loop );
extern void gtk_media_stream_seek_success ( GtkMediaStream* self );
extern void gtk_media_stream_stream_prepared ( GtkMediaStream* self, gboolean has_audio, gboolean has_video, gboolean seekable, gint64 duration );
extern void gtk_media_stream_stream_ended ( GtkMediaStream* self );
extern void gtk_media_stream_unprepared ( GtkMediaStream* self );
extern void gtk_media_stream_stream_unprepared ( GtkMediaStream* self );
extern void gtk_media_stream_set_volume ( GtkMediaStream* self, double volume );
extern void gtk_media_stream_unrealize ( GtkMediaStream* self, GdkSurface* surface );
