extern GtkWidget* gtk_picture_new_for_filename ( const char* filename );
extern GtkWidget* gtk_picture_new_for_file ( GFile* file );
extern GtkWidget* gtk_picture_new_for_paintable ( GdkPaintable* paintable );
extern GtkWidget* gtk_picture_new ( void );
extern GtkWidget* gtk_picture_new_for_resource ( const char* resource_path );
extern GtkWidget* gtk_picture_new_for_pixbuf ( GdkPixbuf* pixbuf );
extern gboolean gtk_picture_get_can_shrink ( GtkPicture* self );
extern const char* gtk_picture_get_alternative_text ( GtkPicture* self );
extern GFile* gtk_picture_get_file ( GtkPicture* self );
extern void gtk_picture_set_alternative_text ( GtkPicture* self, const char* alternative_text );
extern gboolean gtk_picture_get_keep_aspect_ratio ( GtkPicture* self );
extern GdkPaintable* gtk_picture_get_paintable ( GtkPicture* self );
extern void gtk_picture_set_can_shrink ( GtkPicture* self, gboolean can_shrink );
extern void gtk_picture_set_file ( GtkPicture* self, GFile* file );
extern void gtk_picture_set_paintable ( GtkPicture* self, GdkPaintable* paintable );
extern void gtk_picture_set_filename ( GtkPicture* self, const char* filename );
extern void gtk_picture_set_keep_aspect_ratio ( GtkPicture* self, gboolean keep_aspect_ratio );
extern void gtk_picture_set_pixbuf ( GtkPicture* self, GdkPixbuf* pixbuf );
extern void gtk_picture_set_resource ( GtkPicture* self, const char* resource_path );
