extern char* gtk_entry_completion_compute_prefix ( GtkEntryCompletion* completion, const char* key );
extern void gtk_entry_completion_complete ( GtkEntryCompletion* completion );
extern GtkEntryCompletion* gtk_entry_completion_new ( void );
extern gboolean gtk_entry_completion_get_inline_completion ( GtkEntryCompletion* completion );
extern const char* gtk_entry_completion_get_completion_prefix ( GtkEntryCompletion* completion );
extern GtkEntryCompletion* gtk_entry_completion_new_with_area ( GtkCellArea* area );
extern GtkTreeModel* gtk_entry_completion_get_model ( GtkEntryCompletion* completion );
extern gboolean gtk_entry_completion_get_inline_selection ( GtkEntryCompletion* completion );
extern GtkWidget* gtk_entry_completion_get_entry ( GtkEntryCompletion* completion );
extern gboolean gtk_entry_completion_get_popup_single_match ( GtkEntryCompletion* completion );
extern int gtk_entry_completion_get_minimum_key_length ( GtkEntryCompletion* completion );
extern gboolean gtk_entry_completion_get_popup_completion ( GtkEntryCompletion* completion );
extern int gtk_entry_completion_get_text_column ( GtkEntryCompletion* completion );
extern gboolean gtk_entry_completion_get_popup_set_width ( GtkEntryCompletion* completion );
extern void gtk_entry_completion_set_inline_selection ( GtkEntryCompletion* completion, gboolean inline_selection );
extern void gtk_entry_completion_insert_prefix ( GtkEntryCompletion* completion );
extern void gtk_entry_completion_set_minimum_key_length ( GtkEntryCompletion* completion, int length );
extern void gtk_entry_completion_set_inline_completion ( GtkEntryCompletion* completion, gboolean inline_completion );
extern void gtk_entry_completion_set_match_func ( GtkEntryCompletion* completion, GtkEntryCompletionMatchFunc func, gpointer func_data, GDestroyNotify func_notify );
extern void gtk_entry_completion_set_popup_completion ( GtkEntryCompletion* completion, gboolean popup_completion );
extern void gtk_entry_completion_set_model ( GtkEntryCompletion* completion, GtkTreeModel* model );
extern void gtk_entry_completion_set_popup_set_width ( GtkEntryCompletion* completion, gboolean popup_set_width );
extern void gtk_entry_completion_set_popup_single_match ( GtkEntryCompletion* completion, gboolean popup_single_match );
extern void gtk_entry_completion_set_text_column ( GtkEntryCompletion* completion, int column );
