extern void gtk_style_context_get_color ( GtkStyleContext* context, GdkRGBA* color );
extern void gtk_style_context_add_provider ( GtkStyleContext* context, GtkStyleProvider* provider, guint priority );
extern void gtk_style_context_add_class ( GtkStyleContext* context, const char* class_name );
extern void gtk_style_context_get_border ( GtkStyleContext* context, GtkBorder* border );
extern void gtk_style_context_get_margin ( GtkStyleContext* context, GtkBorder* margin );
extern void gtk_style_context_get_padding ( GtkStyleContext* context, GtkBorder* padding );
extern GdkDisplay* gtk_style_context_get_display ( GtkStyleContext* context );
extern int gtk_style_context_get_scale ( GtkStyleContext* context );
extern gboolean gtk_style_context_has_class ( GtkStyleContext* context, const char* class_name );
extern GtkStateFlags gtk_style_context_get_state ( GtkStyleContext* context );
extern void gtk_style_context_remove_class ( GtkStyleContext* context, const char* class_name );
extern void gtk_style_context_remove_provider ( GtkStyleContext* context, GtkStyleProvider* provider );
extern void gtk_style_context_save ( GtkStyleContext* context );
extern gboolean gtk_style_context_lookup_color ( GtkStyleContext* context, const char* color_name, GdkRGBA* color );
extern void gtk_style_context_restore ( GtkStyleContext* context );
extern void gtk_style_context_set_state ( GtkStyleContext* context, GtkStateFlags flags );
extern void gtk_style_context_set_scale ( GtkStyleContext* context, int scale );
extern void gtk_style_context_set_display ( GtkStyleContext* context, GdkDisplay* display );
extern char* gtk_style_context_to_string ( GtkStyleContext* context, GtkStyleContextPrintFlags flags );
