extern GtkWidget * gtk_window_new (void);
extern void gtk_window_set_default_size (GtkWindow *window,gint width,gint height);
extern void gtk_window_set_title (GtkWindow *window, gchar *title);
extern void gtk_window_get_default_size (GtkWindow *window, gint *width, gint *height);
extern void gtk_window_fullscreen(GtkWindow *window);
extern void gtk_window_unfullscreen (GtkWindow *window);
extern void gtk_window_set_resizable(GtkWindow *window, gboolean resizable);
extern gboolean gtk_window_get_resizable(GtkWindow *window);
extern void gtk_window_maximize(GtkWindow *window);
extern void gtk_window_unmaximize(GtkWindow *window);
extern const char* gtk_window_get_title(GtkWindow* window);
extern void gtk_window_close(GtkWindow* window);
extern void gtk_window_destroy(GtkWindow* window);
extern void gtk_window_set_default_size(GtkWindow* window, int width, int height);