extern GtkWidget* gtk_label_new ( const char* str );
extern GtkWidget* gtk_label_new_with_mnemonic ( const char* str );
extern PangoAttrList* gtk_label_get_attributes ( GtkLabel* self );
extern const char* gtk_label_get_current_uri ( GtkLabel* self );
extern PangoEllipsizeMode gtk_label_get_ellipsize ( GtkLabel* self );
extern GMenuModel* gtk_label_get_extra_menu ( GtkLabel* self );
extern GtkJustification gtk_label_get_justify ( GtkLabel* self );
extern const char* gtk_label_get_label ( GtkLabel* self );
extern PangoLayout* gtk_label_get_layout ( GtkLabel* self );
extern void gtk_label_get_layout_offsets ( GtkLabel* self, int* x, int* y );
extern int gtk_label_get_lines ( GtkLabel* self );
extern int gtk_label_get_max_width_chars ( GtkLabel* self );
extern guint gtk_label_get_mnemonic_keyval ( GtkLabel* self );
extern GtkWidget* gtk_label_get_mnemonic_widget ( GtkLabel* self );
extern GtkNaturalWrapMode gtk_label_get_natural_wrap_mode ( GtkLabel* self );
extern gboolean gtk_label_get_selectable ( GtkLabel* self );
extern gboolean gtk_label_get_selection_bounds ( GtkLabel* self, int* start, int* end );
extern gboolean gtk_label_get_single_line_mode ( GtkLabel* self );
extern const char* gtk_label_get_text ( GtkLabel* self );
extern gboolean gtk_label_get_use_markup ( GtkLabel* self );
extern gboolean gtk_label_get_use_underline ( GtkLabel* self );
extern int gtk_label_get_width_chars ( GtkLabel* self );
extern gboolean gtk_label_get_wrap ( GtkLabel* self );
extern PangoWrapMode gtk_label_get_wrap_mode ( GtkLabel* self );
extern float gtk_label_get_xalign ( GtkLabel* self );
extern float gtk_label_get_yalign ( GtkLabel* self );
extern void gtk_label_select_region ( GtkLabel* self, int start_offset, int end_offset );
extern void gtk_label_set_attributes ( GtkLabel* self, PangoAttrList* attrs );
extern void gtk_label_set_ellipsize ( GtkLabel* self, PangoEllipsizeMode mode );
extern void gtk_label_set_extra_menu ( GtkLabel* self, GMenuModel* model );
extern void gtk_label_set_justify ( GtkLabel* self, GtkJustification jtype );
extern void gtk_label_set_label ( GtkLabel* self, const char* str );
extern void gtk_label_set_lines ( GtkLabel* self, int lines );
extern void gtk_label_set_markup ( GtkLabel* self, const char* str );
extern void gtk_label_set_markup_with_mnemonic ( GtkLabel* self, const char* str );
extern void gtk_label_set_max_width_chars ( GtkLabel* self, int n_chars );
extern void gtk_label_set_mnemonic_widget ( GtkLabel* self, GtkWidget* widget );
extern void gtk_label_set_natural_wrap_mode ( GtkLabel* self, GtkNaturalWrapMode wrap_mode );
extern void gtk_label_set_selectable ( GtkLabel* self, gboolean setting );
extern void gtk_label_set_single_line_mode ( GtkLabel* self, gboolean single_line_mode );
extern void gtk_label_set_text ( GtkLabel* self, const char* str );
extern void gtk_label_set_text_with_mnemonic ( GtkLabel* self, const char* str );
extern void gtk_label_set_use_markup ( GtkLabel* self, gboolean setting );
extern void gtk_label_set_use_underline ( GtkLabel* self, gboolean setting );
extern void gtk_label_set_width_chars ( GtkLabel* self, int n_chars );
extern void gtk_label_set_wrap ( GtkLabel* self, gboolean wrap );
extern void gtk_label_set_wrap_mode ( GtkLabel* self, PangoWrapMode wrap_mode );
extern void gtk_label_set_xalign ( GtkLabel* self, float xalign );
extern void gtk_label_set_yalign ( GtkLabel* self, float yalign );
