extern GtkWidget* gtk_label_new(const char* str);
extern void gtk_label_set_markup(GtkLabel* self, const char* str);
extern const char* gtk_label_get_label(GtkLabel* self);
extern const char* gtk_label_get_current_uri(GtkLabel* self);
extern void gtk_label_get_layout_offsets(GtkLabel* self, int* x, int* y);
extern int gtk_label_get_lines(GtkLabel* self);
extern int gtk_label_get_max_width_chars(GtkLabel* self);
extern gboolean gtk_label_get_selectable(GtkLabel* self);
extern gboolean gtk_label_get_selection_bounds(GtkLabel* self, int* start, int* end);
extern gboolean gtk_label_get_single_line_mode(GtkLabel* self);
extern const char* gtk_label_get_text(GtkLabel* self);
extern gboolean gtk_label_get_use_markup(GtkLabel* self);
extern gboolean gtk_label_get_use_underline(GtkLabel* self);
extern int gtk_label_get_width_chars(GtkLabel* self);
extern gboolean gtk_label_get_wrap(GtkLabel* self);
extern float gtk_label_get_xalign(GtkLabel* self);
extern float gtk_label_get_yalign(GtkLabel* self);
extern void gtk_label_select_region(GtkLabel* self, int start_offset, int end_offset);
extern void gtk_label_set_label(GtkLabel* self,const char* str);
extern void gtk_label_set_lines(GtkLabel* self, int lines);
extern void gtk_label_set_markup_with_mnemonic(GtkLabel* self, const char* str);
extern void gtk_label_set_max_width_chars(GtkLabel* self, int n_chars);
extern void gtk_label_set_mnemonic_widget(GtkLabel* self, GtkWidget* widget);
extern void gtk_label_set_selectable(GtkLabel* self, gboolean setting);
extern void gtk_label_set_single_line_mode(GtkLabel* self, gboolean single_line_mode);
extern void gtk_label_set_text(GtkLabel* self, const char* str);
extern void gtk_label_set_text_with_mnemonic(GtkLabel* self, const char* str);
extern void gtk_label_set_use_markup(GtkLabel* self, gboolean setting);
extern void gtk_label_set_use_underline(GtkLabel* self, gboolean setting);
extern void gtk_label_set_width_chars(GtkLabel* self, int n_chars);
extern void gtk_label_set_wrap(GtkLabel* self, gboolean wrap);
extern void gtk_label_set_xalign(GtkLabel* self, float xalign);
extern void gtk_label_set_yalign(GtkLabel* self,float yalign);
