extern GtkWidget* gtk_combo_box_text_new ( void );
extern GtkWidget* gtk_combo_box_text_new_with_entry ( void );
extern void gtk_combo_box_text_append ( GtkComboBoxText* combo_box, const char* id, const char* text );
extern void gtk_combo_box_text_append_text ( GtkComboBoxText* combo_box, const char* text );
extern char* gtk_combo_box_text_get_active_text ( GtkComboBoxText* combo_box );
extern void gtk_combo_box_text_insert ( GtkComboBoxText* combo_box, int position, const char* id, const char* text );
extern void gtk_combo_box_text_insert_text ( GtkComboBoxText* combo_box, int position, const char* text );
extern void gtk_combo_box_text_prepend ( GtkComboBoxText* combo_box, const char* id, const char* text );
extern void gtk_combo_box_text_prepend_text ( GtkComboBoxText* combo_box, const char* text );
extern void gtk_combo_box_text_remove ( GtkComboBoxText* combo_box, int position );
extern void gtk_combo_box_text_remove_all ( GtkComboBoxText* combo_box );
