extern GtkWidget* gtk_stack_new ( void );
extern GtkStackPage* gtk_stack_add_child ( GtkStack* stack, GtkWidget* child );
extern GtkStackPage* gtk_stack_add_named ( GtkStack* stack, GtkWidget* child, const char* name );
extern GtkStackPage* gtk_stack_add_titled ( GtkStack* stack, GtkWidget* child, const char* name, const char* title );
extern GtkWidget* gtk_stack_get_child_by_name ( GtkStack* stack, const char* name );
extern gboolean gtk_stack_get_hhomogeneous ( GtkStack* stack );
extern gboolean gtk_stack_get_interpolate_size ( GtkStack* stack );
extern GtkStackPage* gtk_stack_get_page ( GtkStack* stack, GtkWidget* child );
extern GtkSelectionModel* gtk_stack_get_pages ( GtkStack* stack );
extern guint gtk_stack_get_transition_duration ( GtkStack* stack );
extern gboolean gtk_stack_get_transition_running ( GtkStack* stack );
extern GtkStackTransitionType gtk_stack_get_transition_type ( GtkStack* stack );
extern gboolean gtk_stack_get_vhomogeneous ( GtkStack* stack );
extern GtkWidget* gtk_stack_get_visible_child ( GtkStack* stack );
extern const char* gtk_stack_get_visible_child_name ( GtkStack* stack );
extern void gtk_stack_remove ( GtkStack* stack, GtkWidget* child );
extern void gtk_stack_set_hhomogeneous ( GtkStack* stack, gboolean hhomogeneous );
extern void gtk_stack_set_interpolate_size ( GtkStack* stack, gboolean interpolate_size );
extern void gtk_stack_set_transition_duration ( GtkStack* stack, guint duration );
extern void gtk_stack_set_transition_type ( GtkStack* stack, GtkStackTransitionType transition );
extern void gtk_stack_set_vhomogeneous ( GtkStack* stack, gboolean vhomogeneous );
extern void gtk_stack_set_visible_child ( GtkStack* stack, GtkWidget* child );
extern void gtk_stack_set_visible_child_full ( GtkStack* stack, const char* name, GtkStackTransitionType transition );
extern void gtk_stack_set_visible_child_name ( GtkStack* stack, const char* name );
