extern GtkEntryBuffer* gtk_entry_buffer_new ( const char* initial_chars, int n_initial_chars );
extern guint gtk_entry_buffer_delete_text ( GtkEntryBuffer* buffer, guint position, int n_chars );
extern void gtk_entry_buffer_emit_deleted_text ( GtkEntryBuffer* buffer, guint position, guint n_chars );
extern void gtk_entry_buffer_emit_inserted_text ( GtkEntryBuffer* buffer, guint position, const char* chars, guint n_chars );
extern gsize gtk_entry_buffer_get_bytes ( GtkEntryBuffer* buffer );
extern guint gtk_entry_buffer_get_length ( GtkEntryBuffer* buffer );
extern int gtk_entry_buffer_get_max_length ( GtkEntryBuffer* buffer );
extern const char* gtk_entry_buffer_get_text ( GtkEntryBuffer* buffer );
extern guint gtk_entry_buffer_insert_text ( GtkEntryBuffer* buffer, guint position, const char* chars, int n_chars );
extern void gtk_entry_buffer_set_max_length ( GtkEntryBuffer* buffer, int max_length );
extern void gtk_entry_buffer_set_text ( GtkEntryBuffer* buffer, const char* chars, int n_chars );
