extern GtkWidget* gtk_flow_box_new ( void );
extern void gtk_flow_box_append ( GtkFlowBox* self, GtkWidget* child );
extern void gtk_flow_box_bind_model ( GtkFlowBox* box, GListModel* model, GtkFlowBoxCreateWidgetFunc create_widget_func, gpointer user_data, GDestroyNotify user_data_free_func );
extern gboolean gtk_flow_box_get_activate_on_single_click ( GtkFlowBox* box );
extern GtkFlowBoxChild* gtk_flow_box_get_child_at_index ( GtkFlowBox* box, int idx );
extern GtkFlowBoxChild* gtk_flow_box_get_child_at_pos ( GtkFlowBox* box, int x, int y );
extern guint gtk_flow_box_get_column_spacing ( GtkFlowBox* box );
extern gboolean gtk_flow_box_get_homogeneous ( GtkFlowBox* box );
extern guint gtk_flow_box_get_max_children_per_line ( GtkFlowBox* box );
extern guint gtk_flow_box_get_min_children_per_line ( GtkFlowBox* box );
extern guint gtk_flow_box_get_row_spacing ( GtkFlowBox* box );
extern GList* gtk_flow_box_get_selected_children ( GtkFlowBox* box );
extern GtkSelectionMode gtk_flow_box_get_selection_mode ( GtkFlowBox* box );
extern void gtk_flow_box_insert ( GtkFlowBox* box, GtkWidget* widget, int position );
extern void gtk_flow_box_invalidate_filter ( GtkFlowBox* box );
extern void gtk_flow_box_invalidate_sort ( GtkFlowBox* box );
extern void gtk_flow_box_prepend ( GtkFlowBox* self, GtkWidget* child );
extern void gtk_flow_box_remove ( GtkFlowBox* box, GtkWidget* widget );
extern void gtk_flow_box_select_all ( GtkFlowBox* box );
extern void gtk_flow_box_select_child ( GtkFlowBox* box, GtkFlowBoxChild* child );
extern void gtk_flow_box_selected_foreach ( GtkFlowBox* box, GtkFlowBoxForeachFunc func, gpointer data );
extern void gtk_flow_box_set_activate_on_single_click ( GtkFlowBox* box, gboolean single );
extern void gtk_flow_box_set_column_spacing ( GtkFlowBox* box, guint spacing );
extern void gtk_flow_box_set_filter_func ( GtkFlowBox* box, GtkFlowBoxFilterFunc filter_func, gpointer user_data, GDestroyNotify destroy );
extern void gtk_flow_box_set_hadjustment ( GtkFlowBox* box, GtkAdjustment* adjustment );
extern void gtk_flow_box_set_homogeneous ( GtkFlowBox* box, gboolean homogeneous );
extern void gtk_flow_box_set_max_children_per_line ( GtkFlowBox* box, guint n_children );
extern void gtk_flow_box_set_min_children_per_line ( GtkFlowBox* box, guint n_children );
extern void gtk_flow_box_set_row_spacing ( GtkFlowBox* box, guint spacing );
extern void gtk_flow_box_set_selection_mode ( GtkFlowBox* box, GtkSelectionMode mode );
extern void gtk_flow_box_set_sort_func ( GtkFlowBox* box, GtkFlowBoxSortFunc sort_func, gpointer user_data, GDestroyNotify destroy );
extern void gtk_flow_box_set_vadjustment ( GtkFlowBox* box, GtkAdjustment* adjustment );
extern void gtk_flow_box_unselect_all ( GtkFlowBox* box );
extern void gtk_flow_box_unselect_child ( GtkFlowBox* box, GtkFlowBoxChild* child );
